Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2019-10, with the labels that each got.

#91 fix no return error
  pkg/disk/nodeserver.go
Labels: cncf-cla: yes, lgtm, size/XS

#92 V1.14
  deploy/cpfs/cpfs-plugin.yaml
  deploy/cpfs/cpfs-provisioner.yaml
  deploy/lvm/lvm-plugin.yaml
  deploy/lvm/lvm-provisioner.yaml
  deploy/lvm/resizer/csi-resizer.yaml
  docs/cpfs-dynamic.md
  docs/lvm-resizer.md
  docs/lvm.md
  docs/nas-dynamic.md
  examples/cpfs/deploy.yaml
  examples/cpfs/dynamic/pvc.yaml
  examples/cpfs/dynamic/sc-filesystem.yaml
  examples/cpfs/dynamic/sc-subpath.yaml
  examples/cpfs/pv.yaml
  examples/cpfs/pvc.yaml
  examples/lvm/deploy.yaml
  examples/lvm/pvc.yaml
  examples/lvm/resizer/storageclass.yaml
  examples/lvm/storageclass.yaml
  examples/lvm/striping/pvc.yaml
  examples/lvm/striping/storageclass.yaml
  examples/nas/dynamic/sc-subpath.yaml
  pkg/cpfs/controllerserver.go
  pkg/cpfs/utils.go
  pkg/lvm/controllerserver.go
  pkg/lvm/lvm.go
  pkg/lvm/nodeserver.go
  pkg/lvm/utils.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, size/XXL

#93 update changelog
  CHANGELOG-v1.0.x.md
  README-zh_CN.md
  README.md
Labels: approved, cncf-cla: yes, size/M

#94 update changelog
  CHANGELOG-v1.0.x.md
  README.md
Labels: approved, cncf-cla: yes, size/M

#98 modify subpath mount dir
  pkg/nas/controllerserver.go
Labels: cncf-cla: yes, size/S

#100 update nas docs
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner.yaml
  docs/nas-dynamic.md
  examples/nas/dynamic/sc-filesystem.yaml
Labels: cncf-cla: yes, size/M

#101 add nfs modeType
  docs/nas-dynamic.md
  pkg/disk/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/L

#102 update deploy templates
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/cpfs/cpfs-plugin.yaml
  deploy/disk/disk-plugin.yaml
  deploy/disk/disk-provisioner.yaml
  deploy/lvm/lvm-plugin.yaml
  deploy/lvm/lvm-provisioner.yaml
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner.yaml
  deploy/oss/oss-plugin.yaml
  deploy/rbac.yaml
Labels: approved, cncf-cla: yes, size/M

#104 add option to support delele policy in filesysyem type nas volume
  pkg/nas/controllerserver.go
Labels: cncf-cla: yes, size/M

#107 update nas deploy docs
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner.yaml
  docs/nas-dynamic.md
  examples/nas/dynamic/sc-filesystem.yaml
Labels: cncf-cla: yes, size/XS

#109 update nas delete volume policy
  examples/nas/dynamic/sc-filesystem.yaml
  examples/nas/dynamic/sc-subpath.yaml
  pkg/nas/controllerserver.go
Labels: cncf-cla: yes, size/S

#110 update nas plugin image tag
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner.yaml
Labels: cncf-cla: yes, size/XS

#113 fix code quality issues
  build/oss/csiplugin-connector.go
  main.go
  pkg/cpfs/controllerserver.go
  pkg/cpfs/cpfs.go
  pkg/cpfs/nodeserver.go
  pkg/cpfs/utils.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/lvm/controllerserver.go
  pkg/lvm/lvm.go
  pkg/lvm/nodeserver.go
  pkg/lvm/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
  pkg/oss/utils.go
  pkg/utils/mounter.go
  pkg/utils/util.go
Labels: cncf-cla: yes, size/XXL

#116 update sts verison and add selector
  deploy/lvm/resizer/csi-resizer.yaml
Labels: cncf-cla: yes, size/XS

#117 V1.14
  deploy/lvm/resizer/csi-resizer.yaml
Labels: cncf-cla: yes

#114 change DS version to V1
  deploy/lvm/lvm-plugin.yaml
Labels: cncf-cla: yes, size/XS

#115 change sts apiversion and add selector
  deploy/lvm/lvm-provisioner.yaml
Labels: cncf-cla: yes, size/XS

#118 update to enhance code quality
  main.go
  pkg/cpfs/controllerserver.go
  pkg/cpfs/cpfs.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/lvm/nodeserver.go
  pkg/lvm/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/utils/util.go
Labels: cncf-cla: yes, size/L

#121 request reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS

#123 code qualit checking scripts
  Makefile
  build/oss/csiplugin-connector.go
  hack/check-format.sh
  hack/check-golint.sh
  hack/check-govet.sh
  hack/check-unittest.sh
  hack/run-e2e-test.sh
  hack/update-gofmt.sh
  main.go
  pkg/cpfs/controllerserver.go
  pkg/cpfs/cpfs.go
  pkg/cpfs/nodeserver.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/lvm/controllerserver.go
  pkg/lvm/identityserver.go
  pkg/lvm/lvm.go
  pkg/lvm/utils.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/oss/nodeserver.go
  pkg/oss/nodeserver_test.go
  pkg/oss/oss.go
Labels: approved, cncf-cla: yes, size/L
