Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2019-11, with the labels that each got.

#129 support disk tags
  examples/disk/diskTags/storageclass.yaml
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/M

#130 support lvm nodeAffinity
  deploy/lvm/lvm-plugin.yaml
  docs/lvm.md
  examples/lvm/hapv/storageclass.yaml
  examples/lvm/storageclass.yaml
  go.mod
  go.sum
  pkg/lvm/nodeserver.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role_with_saml.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/get_caller_identity.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_assumed_role_user.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_credentials.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_saml_assertion_info.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/kube-openapi/LICENSE
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/XXL

#133 Refine documents
  CHANGELOG-v1.0.x.md
  README-zh_CN.md
  README.md
Labels: cncf-cla: yes, size/M

#135 Replace github.com/Sirupsen/logrus to github.com/sirupsen/logrus
  go.mod
  go.sum
  main.go
  pkg/cpfs/controllerserver.go
  pkg/cpfs/cpfs.go
  pkg/cpfs/nodeserver.go
  pkg/cpfs/utils.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/identityserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/lvm/controllerserver.go
  pkg/lvm/lvm.go
  pkg/lvm/nodeserver.go
  pkg/lvm/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
  pkg/utils/mounter.go
  pkg/utils/util.go
  vendor/github.com/Sirupsen/logrus/.travis.yml
  vendor/github.com/Sirupsen/logrus/CHANGELOG.md
  vendor/github.com/Sirupsen/logrus/README.md
  vendor/github.com/Sirupsen/logrus/alt_exit.go
  vendor/github.com/Sirupsen/logrus/entry.go
  vendor/github.com/Sirupsen/logrus/exported.go
  vendor/github.com/Sirupsen/logrus/go.mod
  vendor/github.com/Sirupsen/logrus/go.sum
  vendor/github.com/Sirupsen/logrus/json_formatter.go
  vendor/github.com/Sirupsen/logrus/logger.go
  vendor/github.com/Sirupsen/logrus/logrus.go
  vendor/github.com/Sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/Sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/Sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/Sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/Sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/Sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/Sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/Sirupsen/logrus/terminal_windows.go
  vendor/github.com/Sirupsen/logrus/text_formatter.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XL

#137 Fix the Errorf call has arguments but no formatting directives
  .gitignore
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, size/XS

#139 update disk sc avaiable logic
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: cncf-cla: yes, size/XXL

#140 update jisu nas check
  examples/disk/topology/storageclass.yaml
  examples/nas/pv.yaml
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
  pkg/oss/nodeserver.go
Labels: approved, cncf-cla: yes, size/S

#142 fix golint issue
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#143 v1.0.1 release notes
  CHANGELOG-v1.0.x.md
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
Labels: approved, cncf-cla: yes, size/L

#144 Update rbac.yaml
  deploy/rbac.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#145 support unitized endpoint
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/S

#146 support nas unitized endpoint
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/S

#147 support disk mkfsoptions
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/L

#148 support disk mkfsoptions
  examples/disk/options/pv.yaml
  examples/disk/options/storageclass.yaml
Labels: approved, cncf-cla: yes, size/M
