Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#357 Add leaky bucket algorthm to provisioner
  build/ack/Dockerfile
  go.mod
  go.sum
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/utils.go
Labels: cncf-cla: yes, size/L

#358 Fix the bug that the volumeMount print log cannot be found
  pkg/metric/common.go
  pkg/metric/pfsstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#359 add losetup env
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
Labels: approved, cncf-cla: yes, size/M

#360 upgrade snapshot sidercar
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/noleader/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: approved, cncf-cla: yes, size/S

#361 update cpfs config set
  pkg/cpfs/cpfs.go
  pkg/cpfs/nodeserver.go
Labels: approved, cncf-cla: yes, size/S

#363 Add crd create logic
  go.mod
  go.sum
  main.go
  pkg/disk/controllerserver.go
  pkg/disk/crds/snapshot.go
  pkg/disk/disk.go
  pkg/utils/util.go
Labels: cncf-cla: yes, size/XL

#364 Support custom disk create
  go.sum
  pkg/dbfs/controllerserver.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  pkg/nas/controllerserver.go
Labels: cncf-cla: yes, size/L

#365 fixlvm size issue
  pkg/local/controllerserver.go
  pkg/local/lib/commands/commands.go
  pkg/local/nodeserver.go
Labels: approved, cncf-cla: yes, size/M

#367 Remove essd from available
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: cncf-cla: yes, size/XS

#368 update local volume lvm size
  pkg/local/controllerserver.go
  pkg/local/nodeserver.go
Labels: approved, cncf-cla: yes, size/S

#369 Add flexvolume upgrade doc
  docs/migrate/flexvolume-to-csi-disk.md
Labels: cncf-cla: yes, size/XXL

#371 update csi upgrade documents
  deploy/ack/upgrade/upgrade.md
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: approved, cncf-cla: yes, size/L

#374 nas subpath support quota
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/M

#377 update disk template
  deploy/disk/disk-plugin-managed.yaml
  deploy/disk/disk-plugin.yaml
  deploy/disk/disk-provisioner-dedicated.yaml
  deploy/disk/disk-provisioner.yaml
Labels: approved, cncf-cla: yes, size/L

#378 add migrate doc
  docs/migrate/flexvolume-to-csi-empty.md
  docs/migrate/flexvolume-to-csi-nas-oss.md
Labels: approved, cncf-cla: yes, size/XL

#376 Add list snapshot grpc api & refact snapshot code
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, size/L

#375 Feature/io hang
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#379 upgrade yamls
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade.md
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: approved, cncf-cla: yes, size/XXL

#373 Add disk size check after resize request
  go.mod
  go.sum
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/M

#380 security-reinforcement
  deploy/ack/csi-plugin-dedicate.yaml
  deploy/ack/csi-plugin-managed.yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#381 Fix quotapath custom root path
  pkg/local/server/commands.go
  pkg/local/server/commands_test.go
Labels: cncf-cla: yes, size/M

#382 modify default metric is open
  main.go
  pkg/metric/diskstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#383 update template
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  examples/disk/snapshot/snapshotclass.yaml
Labels: approved, cncf-cla: yes, size/M

#384 Feature/default open metric
  build/ack/Dockerfile
  build/ack/entrypoint.sh
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#385 update dbfs umount check
  pkg/dbfs/nodeserver.go
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/S

#386 fix device diff
  pkg/disk/cloud.go
Labels: approved, cncf-cla: yes, size/S

#387 update rbac
  deploy/ack/csi-plugin-dedicate.yaml
  deploy/ack/csi-plugin-managed.yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/rbac.yaml
Labels: approved, cncf-cla: yes, size/M
