Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#280 release v1.0.7
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/mem/mem-plugin.yaml
  deploy/mem/mem-provisioner.yaml
Labels: approved, cncf-cla: yes, size/M

#286 Use REGION_ID environment variable by default when newEcsClient
  pkg/disk/disk.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#287 V1.0.7 lvm upgrade
  build/local/entrypoint.sh
  main.go
  pkg/local/client/grpc.go
  pkg/local/controllerserver.go
  pkg/local/lib/commands/commands.go
  pkg/local/lib/proto/lvm.pb.go
  pkg/local/nodeserver.go
  pkg/local/server/routers.go
Labels: approved, cncf-cla: yes, size/L

#283 Update build all scripts
  build/build-all.sh
  build/build-disk.sh
  build/build-nas.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#282 Feature/container merge
  build/ack/entrypoint.sh
  deploy/ack/csi-plugin-container-merge.yaml
  deploy/ack/csi-provisioner-container-merge.yaml
  main.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#290 csiplugin-connector: add watchdog to watch csi plugin socket liveness
  build/oss/csiplugin-connector.go
  build/oss/entrypoint.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#289 Feature/monitor
  build/build-all.sh
  build/oss/csiplugin-connector.go
  deploy/ack/csi-plugin-container-merge.yaml
  deploy/ack/csi-provisioner-container-merge.yaml
  go.mod
  go.sum
  main.go
  pkg/disk/utils.go
  pkg/metric/collector.go
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
  pkg/metric/metric.go
  pkg/metric/uitls.go
  pkg/utils/util.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#288 Add build function to makefile
  Makefile
Labels: cncf-cla: yes, lgtm, ok-to-test, size/S

#291 csiplugin-connector: sync oss entrypoint.sh to ack
  build/ack/entrypoint.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#297 support kata2.0
  pkg/disk/disk.go
  pkg/nas/nas.go
Labels: approved, cncf-cla: yes, size/XS

#298 support kata 2.0
  pkg/disk/disk.go
  pkg/nas/nas.go
Labels: approved, cncf-cla: yes, size/XS

#293 Add cloud disk snapshot event logic
  deploy/disk/snapshot/csi-snapshotter.yaml
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L
