Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#295 Support upgrade from k8s 1.16 to 1.18
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/XS

#301 Add block device volumeid check
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/M

#309 Add suggestion to openapi error
  build/build-all.sh
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/nas/controllerserver.go
  pkg/utils/error_types.go
  pkg/utils/error_types_test.go
Labels: cncf-cla: yes, size/L

#311 When adding nas tags fails, report events
  go.mod
  pkg/disk/controllerserver.go
  pkg/nas/controllerserver.go
  pkg/utils/util.go
Labels: cncf-cla: yes, ok-to-test, size/L

#312 Fix the bug that the extreme nas subpath cannot be mounted when the s…
  pkg/nas/utils.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#313 After syscall.Mmap is called, ensure that syscall.Munmap is called
  pkg/disk/bdf.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#317 Update deploy shell scripts
  deploy/ack/upgrade/upgrade_csi-plugin-merge.sh
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner-merge.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/disk/disk-plugin-dedicate.yaml
  deploy/disk/disk-plugin-managed.yaml
  deploy/disk/disk-plugin.yaml
  deploy/disk/disk-provisioner-dedicated.yaml
  deploy/disk/disk-provisioner-managed.yaml
  deploy/disk/disk-provisioner.yaml
  deploy/nas/nas-plugin-dedicated.yaml
  deploy/nas/nas-plugin-managed.yaml
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner-dedicated.yaml
  deploy/nas/nas-provisioner-managed.yaml
  deploy/nas/nas-provisioner.yaml
  deploy/oss/oss-plugin-dedicated.yaml
  deploy/oss/oss-plugin-managed.yaml
  deploy/oss/oss-plugin.yaml
Labels: cncf-cla: yes, size/XXL
