Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-06, with the labels that each got.

#251 On non-VF nodes, use device serial to get the disk path
  go.mod
  go.sum
  pkg/disk/bdf.go
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#253 IsVFNode only judges alibaba cloud vendor
  pkg/disk/bdf.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#254 update readme
  README-zh_CN.md
  README.md
Labels: approved, cncf-cla: yes, size/S

#255 V1.0.5 snapshot beta
  deploy/disk/snapshot/crd.yaml
  deploy/disk/snapshot/csi-snapshotter.yaml
  docs/disk-restore.md
  docs/disk-snapshot.md
  examples/disk/snapshot-restore/pvc.yaml
  examples/disk/snapshot-restore/sts-restore.yaml
  examples/disk/snapshot-restore/sts.yaml
  examples/disk/snapshot/snapshot.yaml
  examples/disk/snapshot/snapshotclass.yaml
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: no, size/XL

#257 fix block double mount
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/S

#258 fix block double mount
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/S
