Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#217 support lvm resize
  deploy/local/provisioner.yaml
  pkg/local/lib/commands/commands.go
  pkg/local/nodeserver.go
  pkg/local/server/routers.go
Labels: approved, cncf-cla: yes, size/L

#214 CSI support STS authentication
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
Labels: cncf-cla: yes, ok-to-test, size/M

#216 update disk publish
  pkg/cpfs/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/nas/controllerserver.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/L

#220 update disk availible
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/oss/nodeserver.go
Labels: approved, cncf-cla: yes, size/L

#222 add disk uuid
  build/ack/entrypoint.sh
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#223 support local scheduler
  pkg/local/adapter/scheduler.go
  pkg/local/client/http.go
  pkg/local/controllerserver.go
  pkg/local/controllerutils.go
Labels: approved, cncf-cla: yes, size/L

#224 update runtime logical
  pkg/disk/nodeserver.go
  pkg/nas/nodeserver.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, size/L

#225 update ebs uuid support
  pkg/disk/cloud.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/XS

#226 support RUNTIME env for runc/runc
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  pkg/disk/disk.go
Labels: approved, cncf-cla: yes, size/M

#228 ebs expand offline
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#229 fix: volumeID link path \"/dev/disk/by-id/virtio-XXXX \" not found
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#230 Support serial to find device name
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#232 add disk detach env
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS

#233 fix bdf detach issue
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/S

#236 support disk snapshot/restore
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/L

#237 update snapshot template
  deploy/disk/snapshot/csi-external-snapshot.yaml
  deploy/disk/snapshot/csi-snapshotter.yaml
Labels: approved, cncf-cla: yes, size/L

#238 fix input/output error issue
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/M

#234 Supplement test example
  .travis.yml
  go.mod
  go.sum
  pkg/cpfs/utils_test.go
  pkg/disk/attach_helper_test.go
  pkg/disk/utils_test.go
  pkg/local/controllerutils_test.go
  pkg/lvm/utils_test.go
  pkg/mem/utils_test.go
  pkg/nas/utils_test.go
  pkg/oss/nodeserver_test.go
  pkg/oss/utils_test.go
  pkg/utils/auth_test.go
  pkg/utils/mounter_test.go
  pkg/utils/util_test.go
Labels: cncf-cla: yes, ok-to-test, size/XL

#240 update cpfs driver
  deploy/cpfs/cpfs-plugin.yaml
Labels: approved, cncf-cla: yes, size/XS

#242 update disk block expand
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS

#244 update bdf serial device
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/S

#241 update oss support ubuntu 18.04
  build/oss/dockerfiles/ubuntu-1804
  build/oss/entrypoint.sh
  build/oss/ossfs_1.80.6_ubuntu18.04_amd64.deb
Labels: cncf-cla: yes, lgtm, ok-to-test, size/L
