Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#243 update local volume
  pkg/local/adapter/scheduler.go
  pkg/local/controllerserver.go
  pkg/local/local.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
Labels: approved, cncf-cla: yes, size/L

#259 update local logs
  pkg/local/controllerserver.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/utils.go
  pkg/lvm/nodeserver.go
Labels: approved, cncf-cla: yes, size/M

#262 nas/disk regional support
  pkg/disk/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/M

#263 add storage issue logical
  main.go
  pkg/om/blockvolume.go
  pkg/om/om.go
  pkg/om/orphaned.go
  pkg/om/utils.go
Labels: approved, cncf-cla: yes, size/L

#264 update syconfig logs
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS

#265 Release v1.0.6
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: approved, cncf-cla: yes, size/S

#266 update local volume
  main.go
  pkg/local/adapter/scheduler.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
Labels: approved, cncf-cla: yes, size/XS

#268 fix lvm remove error
  pkg/local/controllerserver.go
  pkg/local/utils.go
Labels: approved, cncf-cla: yes, size/S

#271 fix MountPoint volume remove error
  pkg/local/controllerserver.go
Labels: cncf-cla: yes, ok-to-test, size/S

#272 remove uuid logical
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#275 not fatal when vf check
  pkg/disk/bdf.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#276 update vf check
  pkg/disk/bdf.go
Labels: approved, cncf-cla: yes, size/XS

#273 Add find ecsSnapshot by id
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, ok-to-test, size/M

#277 fix nas dup mount issue
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/S

#278 fix disk snapshot issue
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/M
