Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2020-11, with the labels that each got.

#322 update deploy yaml to 1.10
  deploy/ack/csi-plugin-dedicate.yaml
  deploy/ack/csi-plugin-managed.yaml
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner-container-merge.yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/csi-provisioner.yaml
Labels: approved, cncf-cla: yes, size/XXL

#323 Update upgrade shell & provisioner yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/disk/disk-provisioner-dedicated.yaml
  deploy/disk/disk-provisioner-managed.yaml
Labels: cncf-cla: yes, size/M

#320 Support Kmem type of Pmem
  pkg/local/controllerserver.go
  pkg/local/lib/pmem.go
  pkg/local/local.go
  pkg/local/nodeutils.go
Labels: cncf-cla: yes, size/L

#321 fix typos
  docs/memory.md
  docs/nas-dynamic.md
  examples/nas/dynamic/sc-filesystem-extreme.yaml
  examples/nas/dynamic/sc-filesystem.yaml
  pkg/disk/bdf.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#315 Update ubuntu pkg source
  build/lvm/Dockerfile
Labels: cncf-cla: yes, size/XS

#314 Update rbac.yaml
  deploy/rbac.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#330 fix getMetric no such file or directory
  pkg/metric/diskstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#333 [WIP]Feature/refact local storage
  .travis.yml
  deploy/local/plugin.yaml
  go.mod
  go.sum
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/local/client/grpc.go
  pkg/local/controllerserver.go
  pkg/local/lib/lib_utils.go
  pkg/local/lib/lvm.pb.go
  pkg/local/lib/lvm.proto
  pkg/local/lib/lvm_grpc.pb.go
  pkg/local/lib/pmem.go
  pkg/local/lib/projquota.pb.go
  pkg/local/lib/projquota.proto
  pkg/local/lib/projquota_grpc.pb.go
  pkg/local/local.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/server/commands.go
  pkg/local/server/commands_test.go
  pkg/local/server/routers.go
  pkg/local/server/server.go
  pkg/local/types/types.go
  pkg/local/utils.go
  pkg/mem/mem.go
  pkg/mem/nodeserver.go
  pkg/mem/types.go
  pkg/mem/utils.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/XXL

#336 support kata 2.0
  pkg/disk/disk.go
  pkg/nas/nas.go
Labels: approved, cncf-cla: yes, size/XS

#337 Fix memory fatal issue
  pkg/mem/mem.go
  pkg/mem/nodeserver.go
Labels: cncf-cla: yes, size/XS

#338 update rbac spec
  deploy/rbac.yaml
Labels: approved, cncf-cla: yes, size/XS

#326 Update image prefix & version
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: cncf-cla: yes, size/M

#339 fix nfs remount error
  pkg/nas/utils.go
Labels: approved, cncf-cla: yes, size/XS

#340 fix ecsendpoint format bug
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#341 quotapath support storage schedule
  pkg/local/client/grpc.go
  pkg/local/controllerserver.go
  pkg/local/generator/Readme.md
  pkg/local/generator/pvHandler.go
  pkg/local/generator/pvcHandler.go
  pkg/local/generator/utils.go
  pkg/local/lib/projquota.pb.go
  pkg/local/manager/lib_utils.go
  pkg/local/manager/pmem.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/server/commands.go
  pkg/local/server/routers.go
Labels: approved, cncf-cla: yes, size/L

#343 quotapath support storage schedule
  pkg/local/controllerserver.go
  pkg/local/lib/projquota.pb.go
  pkg/local/lib/projquota.proto
  pkg/local/server/commands.go
Labels: approved, cncf-cla: yes, size/L

#342 Add resize to quotapath and mem
  pkg/local/controllerserver.go
  pkg/local/manager/pmem.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/server/commands.go
  pkg/local/server/commands_test.go
  pkg/utils/util.go
Labels: cncf-cla: yes, size/L

#344 fix deadlock bug
  pkg/metric/pfsstat_collector.go
  pkg/metric/utils.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#346 quotapath resize
  pkg/local/nodeserver.go
Labels: approved, cncf-cla: yes, size/S

#345 Add unit test to grpc & local volume
  pkg/local/client/grpc_test.go
  pkg/local/server/commands.go
Labels: cncf-cla: yes, size/L

#348 Add quota check after quota set
  pkg/local/manager/pmem.go
  pkg/local/server/commands.go
Labels: cncf-cla: yes, size/M

#349 attachments add patch auth
  deploy/ack/csi-plugin-dedicate.yaml
  deploy/ack/csi-plugin-managed.yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/agent/csi-plugin.yaml
  deploy/cpfs/cpfs-plugin.yaml
  deploy/cpfs/cpfs-provisioner.yaml
  deploy/disk/bdf/csi-plugin.yaml
  deploy/disk/bdf/csi-provisioner.yaml
  deploy/disk/disk-plugin-dedicate.yaml
  deploy/disk/disk-plugin-managed.yaml
  deploy/disk/disk-provisioner-dedicated.yaml
  deploy/disk/disk-provisioner-managed.yaml
  deploy/disk/resizer/csi-resizer.yaml
  deploy/disk/snapshot/csi-snapshotter.yaml
  deploy/local/plugin.yaml
  deploy/local/provisioner.yaml
  deploy/lvm/lvm-plugin.yaml
  deploy/lvm/lvm-provisioner.yaml
  deploy/lvm/resizer/csi-resizer.yaml
  deploy/mem/mem-plugin.yaml
  deploy/mem/mem-provisioner.yaml
  deploy/nas/nas-plugin-dedicated.yaml
  deploy/nas/nas-plugin-managed.yaml
  deploy/nas/nas-provisioner-dedicated.yaml
  deploy/nas/nas-provisioner-managed.yaml
  deploy/oss/oss-plugin-dedicated.yaml
  deploy/oss/oss-plugin-managed.yaml
  deploy/rbac.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#350 update local volume logs
  deploy/ack/noleader/csi-provisioner-managed.yaml
  pkg/local/controllerserver.go
  pkg/local/controllerutils.go
  pkg/local/generator/generator.go
  pkg/local/local.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/types/types.go
Labels: approved, cncf-cla: yes, size/XXL

#351 add provisioner without leader select
  deploy/ack/noleader/csi-provisioner-managed.yaml
Labels: approved, cncf-cla: yes, size/XL

#352 fix vol_data_json is invalid bug
  build/ack/Dockerfile
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
  pkg/metric/pfsstat_collector.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#353 update metric volume loop
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/metric/common.go
  pkg/metric/utils.go
Labels: approved, cncf-cla: yes, size/M

#354 support 64 ebs
  pkg/disk/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS

#355 update ack deploy yaml
  deploy/ack/csi-plugin-dedicate.yaml
  deploy/ack/csi-plugin-managed.yaml
  deploy/ack/csi-provisioner-dedicate.yaml
  deploy/ack/csi-provisioner-managed.yaml
  deploy/ack/noleader/csi-provisioner-managed.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: approved, cncf-cla: yes, size/S
