Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#455 update nas template
  deploy/nas/nas-provisioner.yaml
  docs/nas.md
Labels: approved, cncf-cla: yes, size/XS

#456 Feature/support managedfilesystem
  go.mod
  go.sum
  pkg/cnfs/v1alpha1/base.go
  pkg/cnfs/v1alpha1/types.go
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  vendor/github.com/looplab/fsm/.gitignore
  vendor/github.com/looplab/fsm/.travis.yml
  vendor/github.com/looplab/fsm/LICENSE
  vendor/github.com/looplab/fsm/Makefile
  vendor/github.com/looplab/fsm/README.md
  vendor/github.com/looplab/fsm/errors.go
  vendor/github.com/looplab/fsm/event.go
  vendor/github.com/looplab/fsm/fsm.go
  vendor/github.com/looplab/fsm/go.mod
  vendor/github.com/looplab/fsm/graphviz_visualizer.go
  vendor/github.com/looplab/fsm/mermaid_visualizer.go
  vendor/github.com/looplab/fsm/visualizer.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#460 Feature/metric by multi pvc
  pkg/metric/collector.go
  pkg/metric/diskstat_collector.go
  pkg/metric/metric.go
Labels: cncf-cla: yes, size/S

#464 Fix list snapshot error
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, size/XS

#465 Fix loopsetup path error
  pkg/nas/nodeserver.go
Labels: cncf-cla: yes, size/S

#466 Ignore could only be grown by xx fudge error
  pkg/disk/nodeserver.go
Labels: cncf-cla: yes, size/S

#467 sc delete parameter volumeCapacity
  pkg/nas/controllerserver.go
Labels: cncf-cla: yes, size/S
