Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#555 cpfs-add-parameter-validate
  pkg/cpfs/nodeserver.go
  pkg/local/server/commands.go
  pkg/local/server/utils.go
  pkg/utils/util.go
Labels: size/L, cncf-cla: yes

#553 fix repeat update pv annotations
  pkg/local/controllerserver.go
Labels: size/S, ok-to-test, cncf-cla: yes

#542 Fix typo in registry-name in csi-provisioner.yaml
  deploy/ack/csi-provisioner.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, size/XS

#558 update csidriver version to v1
  deploy/ack/csi-plugin.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/agent/csi-plugin.yaml
  deploy/cpfs/cpfs-plugin.yaml
  deploy/disk/bdf/csi-plugin.yaml
  deploy/disk/disk-plugin.yaml
  deploy/local/plugin.yaml
  deploy/lvm/lvm-plugin.yaml
  deploy/mem/mem-plugin.yaml
  deploy/nas/nas-plugin.yaml
  deploy/oss/oss-plugin-ano.yaml
  deploy/oss/oss-plugin.yaml
Labels: approved, size/M, cncf-cla: yes

#559 fix cpfs version, fix ossfs sync data bug and add cpfs validate
  build/cpfs/entrypoint.sh
  build/multi/Dockerfile.multi
  build/multi/amd64-entrypoint.sh
  pkg/cpfs/nodeserver.go
  pkg/nas/nodeserver.go
Labels: size/S, cncf-cla: yes

#560 delete metric nas error log
  pkg/metric/http.go
Labels: cncf-cla: yes, size/XS

#563 support serverless static volume
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: approved, size/M, cncf-cla: yes

#564 Support disk connector
  build/ack/Dockerfile
  build/disk/Dockerfile
  build/multi/Dockerfile.multi
  build/multi/amd64-entrypoint.sh
  build/multi/arm64-entrypoint.sh
  build/multi/csiplugin-connector.go
  build/multi/freezefs.sh
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: size/XXL, cncf-cla: yes
