Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-12, with the labels that each got.

#571 fix staticvolume size diff
  pkg/disk/utils.go
Labels: approved, ok-to-test, cncf-cla: yes, size/XS

#565 Support instant access snapshot for static snapshot
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, size/XS

#570 Fix snapshot recover disks mount
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: size/M, cncf-cla: yes

#574 grpc local dir create
  pkg/local/server/server.go
Labels: approved, cncf-cla: yes, size/XS

#575 add grpc logical
  pkg/local/local.go
Labels: approved, cncf-cla: yes, size/XS

#578 Add custom kubelet root dir yaml
  deploy/customdir/csi-plugin.yaml
Labels: size/L, cncf-cla: yes

#580 modify cpfs version to 2.10.8-205a
  build/cpfs/entrypoint.sh
Labels: lgtm, ok-to-test, cncf-cla: yes, size/XS

#581 local volume support topoloy define
  pkg/local/controllerserver.go
  pkg/local/local.go
  pkg/local/utils.go
Labels: approved, cncf-cla: yes, size/XS

#577 bugfix: use go-ttrpc as client to expand volume
  build/disk/Dockerfile
  go.mod
  go.sum
  pkg/disk/build-proto.sh
  pkg/disk/disk.proto
  pkg/disk/proto/disk.pb.go
  pkg/disk/utils.go
  vendor/github.com/containerd/ttrpc/.gitignore
  vendor/github.com/containerd/ttrpc/LICENSE
  vendor/github.com/containerd/ttrpc/README.md
  vendor/github.com/containerd/ttrpc/channel.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/codec.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/go.mod
  vendor/github.com/containerd/ttrpc/go.sum
  vendor/github.com/containerd/ttrpc/handshake.go
  vendor/github.com/containerd/ttrpc/interceptor.go
  vendor/github.com/containerd/ttrpc/metadata.go
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/github.com/containerd/ttrpc/types.go
  vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.golangci.yml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/buffer_pool.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: needs-ok-to-test, lgtm, size/XXL, cncf-cla: yes

#584 Update yaml version
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/noleader/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
Labels: size/M, cncf-cla: yes

#583 When deleting a subdirectory, the quota limit will be cancelled at the same time.
  pkg/cnfs/v1beta1/base.go
  pkg/metric/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: size/M, cncf-cla: yes

#587 fix only capacity and hibrid nas support quota bug
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
Labels: size/M, cncf-cla: yes
