Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#470 Feature/support aliunx3
  build/ack/Dockerfile
  build/ack/entrypoint.sh
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
Labels: cncf-cla: yes, size/M

#468 Add oss plugin yaml
  deploy/oss/oss-plugin-ano.yaml
Labels: cncf-cla: yes, size/L

#471 Disable force detach disk
  pkg/disk/cloud.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
Labels: cncf-cla: yes, size/S

#472 add bdf volume hang check
  pkg/disk/bdfcheck.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#474 Modify the logic of judging alinux3
  build/ack/entrypoint.sh
Labels: cncf-cla: yes, size/XS

#475 disk support multi tenant
  go.mod
  pkg/disk/bdf.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/utils/auth.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role_with_saml.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/endpoint.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/get_caller_identity.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_assumed_role_user.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_credentials.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_saml_assertion_info.go
  vendor/github.com/looplab/fsm/.gitignore
  vendor/github.com/looplab/fsm/.travis.yml
  vendor/github.com/looplab/fsm/LICENSE
  vendor/github.com/looplab/fsm/Makefile
  vendor/github.com/looplab/fsm/README.md
  vendor/github.com/looplab/fsm/errors.go
  vendor/github.com/looplab/fsm/event.go
  vendor/github.com/looplab/fsm/fsm.go
  vendor/github.com/looplab/fsm/go.mod
  vendor/github.com/looplab/fsm/graphviz_visualizer.go
  vendor/github.com/looplab/fsm/mermaid_visualizer.go
  vendor/github.com/looplab/fsm/visualizer.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/XXL

#476 support kubelt root dir
  main.go
  pkg/dbfs/nodeserver.go
  pkg/disk/bdfcheck.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
  pkg/metric/metric.go
  pkg/metric/mountstats.go
  pkg/metric/pfsstat_collector.go
  pkg/metric/utils.go
  pkg/om/blockvolume.go
  pkg/om/orphaned.go
  pkg/oss/nodeserver.go
  pkg/utils/global.go
Labels: approved, cncf-cla: yes, size/L

#477 Release v1.1.4 bdf hang check
  pkg/disk/bdf.go
  pkg/disk/bdfcheck.go
Labels: approved, cncf-cla: yes, size/L

#478 bdf check add tags
  pkg/disk/bdfcheck.go
Labels: approved, cncf-cla: yes, size/M

#480 bdf check add tags
  pkg/disk/bdfcheck.go
Labels: approved, cncf-cla: yes, size/L

#481 update bdf hang check
  pkg/disk/bdf.go
  pkg/disk/bdfcheck.go
Labels: approved, cncf-cla: yes, size/L

#482 fix dbfs noexist issue
  pkg/dbfs/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#484 support-TrashCanReservedDays
  pkg/cnfs/v1alpha1/types.go
Labels: cncf-cla: yes, size/M

#483 support disk support from pvc labes
  pkg/disk/controllerserver.go
Labels: approved, cncf-cla: yes, size/M

#485 local volume support topo define
  pkg/local/local.go
  pkg/local/nodeserver.go
  pkg/local/types/types.go
Labels: approved, cncf-cla: yes, size/M

#486 local support base image update
  build/local/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#487 modify-cnfs-version-to-v1beta1
  pkg/cnfs/v1beta1/base.go
  pkg/cnfs/v1beta1/types.go
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: cncf-cla: yes, size/S

#490 add TrashCanReservedDays field and modify cnfs version to v1beta1
  pkg/cnfs/v1beta1/base.go
  pkg/cnfs/v1beta1/types.go
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: cncf-cla: yes, size/M

#488 disk snapshot crd install optional
  pkg/disk/controllerserver.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, size/S

#491 add cnfs volume delete
  pkg/nas/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#492 fix dbfs no exist issue
  pkg/dbfs/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#493 fix ossfs dont sync data bug
  build/ack/Dockerfile
  build/ack/entrypoint.sh
Labels: cncf-cla: yes, size/XS
