Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#518 Release v1.1.4
  build/oss/csiplugin-connector.go
  go.mod
  go.sum
  main.go
  pkg/metric/common.go
  pkg/metric/diskstat_collector.go
  pkg/metric/http.go
  pkg/metric/metric.go
  pkg/metric/nfsstats_collector.go
  pkg/metric/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
Labels: size/L, cncf-cla: yes

#517 Add retry for obtain metadata info from metadata server
  pkg/cpfs/cpfs.go
  pkg/dbfs/dbfs.go
  pkg/disk/disk.go
  pkg/local/local.go
  pkg/mem/mem.go
  pkg/nas/nas.go
  pkg/oss/oss.go
  pkg/utils/util.go
Labels: size/M, cncf-cla: yes

#521 Adapter for fin error
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/XS

#524 support nodeserver retry
  pkg/disk/nodeserver.go
Labels: size/S, approved, cncf-cla: yes

#525 support nodeserver retry
  pkg/disk/nodeserver.go
  pkg/nas/utils.go
  pkg/utils/util.go
Labels: approved, size/M, cncf-cla: yes

#528 Support external provisioner v3.0.0
  deploy/ack/csi-provisioner.yaml
  deploy/cpfs/cpfs-provisioner.yaml
  deploy/disk/disk-provisioner.yaml
  deploy/local/provisioner.yaml
  deploy/lvm/lvm-provisioner.yaml
  deploy/mem/mem-provisioner.yaml
  deploy/nas/nas-provisioner.yaml
Labels: size/M, cncf-cla: yes

#530 Remove csi-provisioner 1.6.0 in all yaml
  deploy/ack/install/Readme.md
  deploy/ack/noleader/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  docs/migrate/flexvolume-to-csi-disk.md
Labels: size/M, cncf-cla: yes

#531 Update snapshot metadata
  pkg/disk/controllerserver.go
Labels: size/S, cncf-cla: yes

#526 ia snapshot support
  go.mod
  go.sum
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/generic.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1beta1/interface.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1/expansion_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1beta1/expansion_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/listers/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes

#535 if nas disk pvc is unbound status, judge mountpath is empty.
  pkg/metric/diskstat_collector.go
  pkg/metric/nfsstats_collector.go
  pkg/metric/pfsstat_collector.go
Labels: cncf-cla: yes, size/XS

#537 Create default VolumeSnapshotClass in provisioner initialize
  deploy/ack/csi-plugin.yaml
  deploy/rbac.yaml
  pkg/disk/controllerserver.go
Labels: lgtm, size/S, cncf-cla: yes
