Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#494 Support to specify ARN parameters when CreateDisk
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#496 add disk init tools
  tools/disk-auto-init/main.go
Labels: approved, cncf-cla: yes, size/L

#489 support lifsea os
  build/ack/entrypoint.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#497 Reinforce update node support disk type
  pkg/disk/utils.go
Labels: size/M, cncf-cla: yes

#499 Fix driver forced convert type panic
  build/build-all.sh
  pkg/cpfs/controllerserver.go
  pkg/nas/controllerserver.go
Labels: size/S, cncf-cla: yes

#502 Support xfs filesystem quotapath
  pkg/local/server/commands.go
  pkg/local/server/commands_test.go
Labels: size/M, cncf-cla: yes

#503 Add ecs endpoint support for inner use
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/XS

#504 Add ep to regionid on inner use
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/XS

#501 Support xfs filesystem quotapath
  pkg/local/server/commands.go
  pkg/local/server/commands_test.go
Labels: size/M, cncf-cla: yes

#505 Add instanceid to NodeServer
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: cncf-cla: yes, size/XS

#509 Remove fsck cmd
  pkg/nas/nodeserver.go
Labels: size/S, cncf-cla: yes

#510 Add nas losetup fsck during mount
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: size/M, cncf-cla: yes
