Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#449 support all region vpc endpoint
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/S

#451 update templates
  README-zh_CN.md
  README.md
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade.md
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/nas/nas-plugin-dedicated.yaml
  deploy/nas/nas-plugin-managed.yaml
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner-dedicated.yaml
  deploy/nas/nas-provisioner.yaml
  deploy/oss/oss-plugin.yaml
Labels: approved, cncf-cla: yes, size/XL

#452 V1.1.3 template update
  README-zh_CN.md
  README.md
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade.md
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/nas/nas-plugin-dedicated.yaml
  deploy/nas/nas-plugin-managed.yaml
  deploy/nas/nas-plugin.yaml
  deploy/nas/nas-provisioner-dedicated.yaml
  deploy/nas/nas-provisioner.yaml
  deploy/oss/oss-plugin.yaml
Labels: approved, size/XL

#450 Upgrade snapshot crd version
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/ack/upgrade/upgrade_csi-provisioner.sh
  deploy/rbac.yaml
  pkg/disk/controllerserver.go
  pkg/disk/crds/snapshot.go
Labels: cncf-cla: yes, size/XXL

#454 update nas template
  docs/nas.md
Labels: approved, cncf-cla: yes, size/S
