Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-08, with the labels that each got.

#683 mutex saveOssfsCredential and uniqOssfsCredential
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
Labels: size/S, cncf-cla: yes

#684 mutex saveOssfsCredential and uniqOssfsCredential
  pkg/oss/nodeserver.go
Labels: size/S, cncf-cla: yes

#687 chore: Support log mount options & fix private build
  build/multi-private/Dockerfile.multi
  pkg/disk/utils.go
Labels: kind/bug, cncf-cla: yes, size/XS

#688 add ossfs metrics
  build/amd/Dockerfile
  build/build-all-amd.sh
  build/lib/amd64-entrypoint.sh
  pkg/metric/alinas_stat_collector.go
  pkg/metric/common.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/fuse_stat_collector.go
  pkg/metric/nfs_stat_collector.go
  pkg/metric/pfs_stat_collector.go
  pkg/metric/utils.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/utils/util.go
Labels: size/XL, cncf-cla: yes

#685 Feature/rich nas client
  pkg/dbfs/utils.go
  pkg/disk/utils.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/nfs_stat_collector.go
  pkg/nas/utils.go
Labels: cncf-cla: yes, size/XS

#686 Add func: allow auto snapshot during expanding volume.
  main.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: kind/feature, needs-ok-to-test, lgtm, size/L, cncf-cla: yes

#691 Feature/support kylin and uos
  build/multi-private/Dockerfile.multi
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
  build/multi-private/arm64-ossfs-8u
  build/multi-private/libstdc++.so.6.0.28
Labels: cncf-cla: no, size/M

#692 add head file top metrics
  build/build-all-amd.sh
  pkg/disk/bdfcheck.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/ens/nodeserver.go
  pkg/ens/utils.go
  pkg/metric/alinas_stat_collector.go
  pkg/metric/common.go
  pkg/metric/fuse_stat_collector.go
Labels: size/L, cncf-cla: yes

#693 fix kylin/uos entrypoint in amd64
  build/multi-private/amd64-entrypoint.sh
Labels: cncf-cla: no, size/XS

#694 Support globalmount path changed in k8s 1.24
  pkg/disk/nodeserver.go
Labels: size/M, cncf-cla: yes
