Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#634 support multi attach disk
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: approved, size/L, cncf-cla: yes

#665 Support dbfs vpc domain
  pkg/dbfs/dbfs.go
Labels: kind/bug, cncf-cla: yes, size/XS

#664 Support oxs node instance label & zoneid label
  pkg/disk/utils.go
Labels: kind/feature, cncf-cla: yes, size/XS

#662 Fix fuse devel install
  build/lib/arm64-entrypoint.sh
Labels: cncf-cla: yes, size/XS

#669 Fix create disk client token elements
  pkg/disk/controllerserver.go
Labels: cncf-cla: yes, size/XS

#671 modify print log diskResponse to instanceResponse
  pkg/disk/bdf.go
Labels: cncf-cla: yes, size/XS

#672 Disable global var access to metadata server
  pkg/local/capacity.go
Labels: cncf-cla: yes, size/XS
