Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#645 support cpfs nfs
  build/amd/Dockerfile
  build/lib/amd64-entrypoint.sh
Labels: approved, cncf-cla: yes, size/XS

#646 support cpfs nfs
  build/build-all-amd.sh
  build/lib/aliyun-alinas-utils-1.1-2.al7.noarch.rpm
  build/lib/amd64-entrypoint.sh
  pkg/nas/nas.go
Labels: size/S, approved, cncf-cla: yes

#647 support cpfs nfs
  build/multi/Dockerfile.multi
Labels: size/S, approved, cncf-cla: yes

#648 support cpfs nfs
  build/multi/Dockerfile.multi
Labels: approved, cncf-cla: yes, size/XS

#649 fix local device lower key
  pkg/local/controllerserver.go
  pkg/local/controllerutils.go
  pkg/local/nodeutils.go
Labels: size/S, approved, cncf-cla: yes

#650 nas skip mount mode
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: approved, size/M, cncf-cla: yes

#651 Support dbfs node max volume config
  build/multi/Dockerfile.multi
  pkg/dbfs/nodeserver.go
  pkg/dbfs/utils.go
  pkg/disk/controllerserver.go
Labels: kind/feature, size/L, cncf-cla: yes

#652 nas skip mount mode
  pkg/nas/nodeserver.go
Labels: approved, cncf-cla: yes, size/XS

#655 go build use vendor
  build/multi/Dockerfile.multi
Labels: cncf-cla: yes, size/XS

#658 Feature/rich nas client
  pkg/nas/nas.go
Labels: size/S, cncf-cla: yes

#660 fix local device remount
  pkg/local/nodeutils.go
Labels: size/S, approved, cncf-cla: yes
