Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-01, with the labels that each got.

#588 optimize duplicate code
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: needs-ok-to-test, size/M, cncf-cla: yes

#586 support lvm io limit
  pkg/local/nodeutils.go
  pkg/local/utils.go
Labels: approved, size/L, cncf-cla: yes

#589 Add PR and issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs-ok-to-test, lgtm, size/L, cncf-cla: yes

#572 Adapt to openshift, read ak from /root/.alibabacloud/credentials path.
  go.sum
  pkg/dbfs/dbfs.go
  pkg/dbfs/utils.go
  pkg/disk/disk.go
  pkg/disk/utils.go
  pkg/local/utils.go
  pkg/lvm/utils.go
  pkg/nas/nas.go
  pkg/nas/utils.go
  pkg/oss/nodeserver.go
  pkg/utils/auth.go
  pkg/utils/auth_test.go
  pkg/utils/util.go
  tools/disk-auto-init/main.go
Labels: size/L, cncf-cla: yes

#590 Add source pvc disk size to snapshot restore size
  pkg/disk/controllerserver.go
Labels: kind/bug, cncf-cla: yes, size/XS

#595 update v1.1.5 templates
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
Labels: approved, size/L, cncf-cla: yes

#597 update v1.1.5 templates
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
Labels: approved, size/L

#598 update templates
  deploy/ack/csi-provisioner.yaml
Labels: approved, cncf-cla: yes, size/XS

#599 update images
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
Labels: approved, cncf-cla: yes, size/XS
