Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#713 Support custom snapshot retention
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/utils/util.go
Labels: kind/feature, size/M, cncf-cla: yes

#712 chore: Add `.dockerignore`
  .dockerignore
Labels: kind/feature, needs-ok-to-test, lgtm, cncf-cla: yes, size/XS

#715 support anolis images
  build/lib/amd64-entrypoint.sh
  build/multi-private/amd64-entrypoint.sh
Labels: size/S, cncf-cla: yes

#716 anolis use centos8 ossfs binary
  build/lib/amd64-entrypoint.sh
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
Labels: size/S, cncf-cla: yes
