Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#695 Fix globalmount path usage
  pkg/dbfs/nodeserver.go
  pkg/ens/nodeserver.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/utils.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
Labels: kind/bug, size/M, cncf-cla: yes

#696 modified fsfreeze.sh for advancedSnapshot.
  build/lib/amd64-entrypoint.sh
  build/lib/freezefs.sh
Labels: kind/bug, needs-ok-to-test, size/S, cncf-cla: yes

#697 Add host command var
  build/multi-private/arm64-entrypoint.sh
Labels: cncf-cla: yes, size/XS

#698 add cnfs oss feature
  pkg/cnfs/v1beta1/base.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
Labels: size/L, cncf-cla: yes

#699 use http in private cloud
  pkg/dbfs/utils.go
  pkg/disk/utils.go
  pkg/nas/utils.go
  pkg/utils/auth.go
Labels: cncf-cla: no, size/S

#703 Fix const instanceid
  pkg/disk/cloud.go
Labels: kind/bug, cncf-cla: yes, size/XS

#701 broken link issue resolved
  CONTRIBUTING.md
Labels: needs-ok-to-test, lgtm, cncf-cla: yes, size/XS

#704 update eac version from 1.0.1 to 1.0.2
  build/lib/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
  pkg/nas/nas.go
Labels: cncf-cla: yes, size/XS

#705 modify don't install eac by default
  pkg/nas/nas.go
Labels: size/M, cncf-cla: yes

#690 feature: Add oidc auth method to csi (only inner use)
  build/multi/Dockerfile.multi.asi
  go.mod
  go.sum
  pkg/auth/client.go
  pkg/auth/oidc.go
  pkg/auth/singleton.go
  pkg/disk/utils.go
  pkg/utils/auth.go
  pkg/utils/auth_test.go
  vendor/github.com/h2non/parth/LICENSE
  vendor/github.com/h2non/parth/README.md
  vendor/github.com/h2non/parth/go.mod
  vendor/github.com/h2non/parth/parth.go
  vendor/github.com/h2non/parth/segindex.go
  vendor/github.com/h2non/parth/segtostr.go
  vendor/gopkg.in/h2non/gock.v1/.editorconfig
  vendor/gopkg.in/h2non/gock.v1/.gitignore
  vendor/gopkg.in/h2non/gock.v1/.travis.yml
  vendor/gopkg.in/h2non/gock.v1/History.md
  vendor/gopkg.in/h2non/gock.v1/LICENSE
  vendor/gopkg.in/h2non/gock.v1/README.md
  vendor/gopkg.in/h2non/gock.v1/go.mod
  vendor/gopkg.in/h2non/gock.v1/gock.go
  vendor/gopkg.in/h2non/gock.v1/matcher.go
  vendor/gopkg.in/h2non/gock.v1/matchers.go
  vendor/gopkg.in/h2non/gock.v1/mock.go
  vendor/gopkg.in/h2non/gock.v1/options.go
  vendor/gopkg.in/h2non/gock.v1/request.go
  vendor/gopkg.in/h2non/gock.v1/responder.go
  vendor/gopkg.in/h2non/gock.v1/response.go
  vendor/gopkg.in/h2non/gock.v1/store.go
  vendor/gopkg.in/h2non/gock.v1/transport.go
  vendor/gopkg.in/h2non/gock.v1/version.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, cncf-cla: yes
