Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#659 fix rund remount
  pkg/disk/nodeserver.go
  pkg/utils/util.go
Labels: lgtm, size/S, approved, cncf-cla: yes

#674 modify arm64 /bin/csiplugin-connector to /csi/csiplugin-connector
  build/lib/arm64-entrypoint.sh
Labels: size/S, cncf-cla: yes

#675 modify delete eac and alinas-utils before install
  pkg/nas/nas.go
Labels: cncf-cla: yes, size/XS

#676 modify parse eac metric uuid:server format
  build/amd/Dockerfile
  build/lib/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
  pkg/dadi/dadi.go
  pkg/metric/alinas_stat_collector.go
  pkg/nas/nas.go
Labels: size/S, cncf-cla: yes

#673 Feature/support disk waiting during mount
  go.mod
  go.sum
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/mount-utils/LICENSE
  vendor/k8s.io/mount-utils/OWNERS
  vendor/k8s.io/mount-utils/README.md
  vendor/k8s.io/mount-utils/SECURITY_CONTACTS
  vendor/k8s.io/mount-utils/code-of-conduct.md
  vendor/k8s.io/mount-utils/doc.go
  vendor/k8s.io/mount-utils/fake_mounter.go
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_unsupported.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/k8s.io/mount-utils/resizefs_unsupported.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, cncf-cla: yes

#678 fix shell spaces bug
  build/lib/amd64-entrypoint.sh
Labels: cncf-cla: yes, size/XS

#679 fix a typo in the log of NodePublishVolume
  pkg/disk/nodeserver.go
  pkg/nas/nodeserver.go
Labels: kind/bug, needs-ok-to-test, lgtm, cncf-cla: yes, size/XS

#681 Feature/support disk instance detach check
  build/lib/arm64-entrypoint.sh
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/utils/io.go
Labels: kind/feature, size/M, cncf-cla: yes

#682 fix provisioner metrics can not use bug
  build/lib/csiplugin-connector.go
  build/oss/csiplugin-connector.go
  main.go
  pkg/cnfs/v1beta1/base.go
  pkg/cnfs/v1beta1/types.go
  pkg/cpfs/controllerserver.go
  pkg/cpfs/utils.go
  pkg/dbfs/controllerserver.go
  pkg/dbfs/dbfs.go
  pkg/dbfs/nodeserver.go
  pkg/disk/disk.go
  pkg/disk/disk_test.go
  pkg/disk/utils_test.go
  pkg/local/capacity.go
  pkg/local/client/grpc.go
  pkg/local/client/http.go
  pkg/metric/alinas_stat_collector.go
  pkg/metric/collector.go
  pkg/metric/common.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/http.go
  pkg/metric/metric.go
  pkg/metric/mountstats.go
  pkg/metric/pfs_stat_collector.go
  pkg/metric/unix_domain_socket.go
  pkg/nas/controllerserver.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/nas/nodeserver_test.go
  pkg/nas/utils.go
  pkg/nas/utils_test.go
  pkg/oss/nodeserver.go
  pkg/oss/nodeserver_test.go
  pkg/utils/util.go
Labels: size/L, cncf-cla: yes
