Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#717 1. If the endpoint of ecs is the same as that of oss, use the public …
  build/amd/Dockerfile
  build/build-all-amd.sh
  build/lib/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  pkg/nas/nas.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
Labels: size/L, cncf-cla: yes

#718 Upgrade baseimg from centos7 to alinux3
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  pkg/disk/cloud.go
Labels: size/S, cncf-cla: yes

#720 Upgrade oidc isolate token
  build/multi/Dockerfile.multi.asi
Labels: kind/bug, cncf-cla: yes, size/XS

#719 Fix disk resize err
  pkg/disk/nodeserver.go
Labels: cncf-cla: yes, size/XS
