Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#706 Improve/use lvm fast format
  build/lib/amd64-entrypoint.sh
  deploy/ack/csi-plugin.yaml
  deploy/ack/csi-provisioner.yaml
  go.sum
  main.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/ens/nodeserver.go
  pkg/local/local.go
  pkg/local/manager/lib_utils.go
  pkg/local/manager/pmem.go
  pkg/local/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/utils.go
  pkg/local/utils_test.go
  pkg/utils/auth.go
  pkg/utils/auth_test.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: kind/feature, size/XL, cncf-cla: yes

#709 add kylin OS support on bare metal
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
  pkg/nas/utils.go
Labels: kind/feature, needs-ok-to-test, size/S, cncf-cla: yes

#710 Stop applying the beta.kubernetes.io/os
  deploy/ack/csi-plugin.yaml
  deploy/ack/upgrade/upgrade_csi-plugin.sh
  deploy/dbfs/csi-plugin.yaml
  deploy/disk/disk-plugin.yaml
  deploy/ens/csi-plugin.yaml
  deploy/local/plugin.yaml
  deploy/nas/nas-plugin.yaml
  deploy/oss/oss-plugin-ano.yaml
  deploy/oss/oss-plugin.yaml
  docs/migrate/flexvolume-to-csi-disk.md
Labels: lgtm, size/S, kind/cleanup, cncf-cla: yes
