Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#612 support multi-zones node for virtual node
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: needs-ok-to-test, lgtm, size/L, cncf-cla: yes

#621 update storage capacity tag
  pkg/local/capacity.go
Labels: approved, cncf-cla: yes, size/XS

#622 create disk type by order
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: size/S, approved, cncf-cla: yes

#624 update disktype label
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/XS

#625 update disktype label
  pkg/disk/utils.go
Labels: approved, cncf-cla: yes, size/XS

#626 static volume support snapshot
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: approved, size/M, cncf-cla: yes

#630 local volume cache NodeAddr
  hack/check-golint.sh
  pkg/utils/util.go
Labels: size/S, approved, cncf-cla: yes

#627 disk support iolimit
  pkg/disk/nodeserver.go
  pkg/local/nodeutils.go
  pkg/local/utils.go
  pkg/utils/io.go
Labels: approved, size/L, cncf-cla: yes

#628 Add a parameter to the schema to automatically increase volume sizes …
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  vendor/modules.txt
Labels: kind/feature, ok-to-test, size/M, cncf-cla: yes

#632 Add kubecli qps setting for csi
  pkg/disk/disk.go
  pkg/local/controllerserver.go
  pkg/local/local.go
  pkg/local/nodeserver.go
  pkg/local/secret.go
  pkg/nas/nas.go
Labels: kind/feature, size/M, cncf-cla: yes
