Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#875 Feature: ignore tmpfs mountpoint check
  pkg/disk/nodeserver.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#881 add a manifest that we can run csi-sanity in k8s
  test/csi-sanity/csi-sanity-disk.yaml
Labels: needs-ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#879 Centralized Node Metadata Provider
  go.mod
  go.sum
  main.go
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/cloud/metadata/ecs.go
  pkg/cloud/metadata/ecs_test.go
  pkg/cloud/metadata/env.go
  pkg/cloud/metadata/env_test.go
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/k8s_test.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/cloud/metadata/openapi.go
  pkg/cloud/metadata/openapi_test.go
  pkg/disk/constants.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  vendor/github.com/jarcoal/httpmock/.gitignore
  vendor/github.com/jarcoal/httpmock/LICENSE
  vendor/github.com/jarcoal/httpmock/README.md
  vendor/github.com/jarcoal/httpmock/any.go
  vendor/github.com/jarcoal/httpmock/doc.go
  vendor/github.com/jarcoal/httpmock/env.go
  vendor/github.com/jarcoal/httpmock/file.go
  vendor/github.com/jarcoal/httpmock/internal/error.go
  vendor/github.com/jarcoal/httpmock/internal/route_key.go
  vendor/github.com/jarcoal/httpmock/internal/stack_tracer.go
  vendor/github.com/jarcoal/httpmock/internal/submatches.go
  vendor/github.com/jarcoal/httpmock/match.go
  vendor/github.com/jarcoal/httpmock/response.go
  vendor/github.com/jarcoal/httpmock/transport.go
  vendor/modules.txt
Labels: needs-ok-to-test, lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#885 metadata: add logging and cache
  pkg/cloud/metadata/ecs.go
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/openapi.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/M, cncf-cla: yes

#887 feat: visit storage-monitor using clusterIP instead of domain name
  pkg/metric/http.go
  pkg/metric/monitor_client.go
  pkg/metric/nfs_stat_collector.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#882 oss: support CoCo direct volume feature
  pkg/oss/coco.go
  pkg/oss/coco_test.go
  pkg/oss/nodeserver.go
  pkg/utils/kata/directvolume/direct_volume.go
  pkg/utils/kata/directvolume/utils.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/L, cncf-cla: yes

#889 feature: Lowering the minimum essd-pl0 capacity limit
  pkg/disk/constants.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#891 Fix IO limits not effective
  pkg/utils/io.go
  pkg/utils/util.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#890 feature: support reschedule disk with resource exhausted error in del…
  pkg/disk/cloud.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#893 retry alinas-utils installation
  build/lib/amd64-entrypoint.sh
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#892 Feature: narrow down reschedule scenario
  pkg/disk/cloud.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#895 Feature: support restricted resource code error retry
  pkg/disk/constants.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#896 fix host_os detection
  build/lib/amd64-entrypoint.sh
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#897 Cleanup: support read kubecfg from command line
  pkg/oss/controllerserver.go
Labels: size/S, kind/cleanup, approved, cncf-cla: yes

#883 disk: refactor config options
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/utils/config.go
Labels: kind/bug, needs-ok-to-test, lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#904 utils: fix guaranteed QoS blkio cgroup path
  pkg/utils/io.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, approved, cncf-cla: yes
