Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#762 Chore: adjust cluster role
  deploy/rbac.yaml
Labels: kind/cleanup, size/M, cncf-cla: yes

#764 fix data race in metrics server
  pkg/metric/disk_stat_collector.go
  pkg/metric/nfs_stat_collector.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/M, cncf-cla: yes

#765 Chore: Add xfs custom mkfs args
  pkg/disk/nodeserver.go
  pkg/utils/util.go
Labels: kind/feature, size/M, cncf-cla: yes

#766 Garbage collecting for lvm/loopdevice volumes
  pkg/local/gc/gc.go
  pkg/local/gc/loopdevice.go
  pkg/local/gc/lvm.go
  pkg/local/manager/loopdevice.go
  pkg/local/nodeserver.go
  pkg/local/server/commands.go
Labels: kind/feature, needs-ok-to-test, lgtm, size/L, cncf-cla: yes

#769 fix metrics bug for multi mountpoint
  pkg/metric/nfs_stat_collector.go
Labels: size/S, cncf-cla: yes

#770 Improve lvm gc log when VG not found
  pkg/local/gc/lvm.go
Labels: needs-ok-to-test, lgtm, size/S, kind/cleanup, cncf-cla: yes

#771 Chore: Add vfhp rpm install
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: size/S, kind/cleanup, cncf-cla: yes

#772 Chore/change vfhp address
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: kind/feature, size/M, cncf-cla: yes

#777 Start vfhp hotplugin & Fix shared disk yaml
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
  examples/disk/shared-disk/pv.yaml
  examples/disk/shared-disk/pvc.yaml
  examples/disk/shared-disk/storageclass.yaml
Labels: kind/cleanup, size/M, cncf-cla: yes

#778 Feature/fix non official ecs cases
  deploy/ecs/csi-driver.yaml
  deploy/ecs/csi-plugin.yaml
  deploy/ecs/csi-provisioner.yaml
  deploy/ecs/rbac.yaml
  deploy/nonecs/csi-driver.yaml
  deploy/nonecs/csi-plugin.yaml
  deploy/nonecs/csi-provisioner.yaml
  deploy/nonecs/rbac.yaml
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
Labels: kind/feature, size/XL, cncf-cla: yes
