Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#919 disable podInformer in external-resizer
  deploy/ecs/csi-provisioner.yaml
  deploy/nonecs/csi-provisioner.yaml
Labels: needs-ok-to-test, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#922 fix(nas): set /proc/sys/sunrpc/tcp_slot_table_entries to 128
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#917 disk: fix parameter checks in NewNodeServer
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: kind/bug, lgtm, size/S, approved, ok-to-test, cncf-cla: yes

#925 fix: support sts authtype in containerized version
  pkg/mounter/fuse_containerized_mounter.go
  pkg/mounter/ossfs.go
  pkg/mounter/ossfs_test.go
  pkg/oss/nodeserver.go
  pkg/oss/nodeserver_test.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#924 fix: configure mlocate cron.daily
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#926 feat-oss: encryption kms, aes236, byok
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#929 metadata: support for old ecs-instance-id label
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/k8s_test.go
Labels: kind/feature, needs-ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#928 support customized annotations and labels on fuse pod
  build/fuse-clients/ossfs/Dockerfile
  build/fuse-clients/ossfs/entrypoint.sh
  pkg/mounter/fuse_containerized_mounter.go
  pkg/mounter/fuse_containerized_mounter_test.go
  pkg/mounter/helper.go
  pkg/mounter/ossfs.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#932 build(asi): update dockerfile
  build/multi/Dockerfile.multi.asi
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#933 ossfs entrypoint should not delay termination if no mountpoints
  build/fuse-clients/ossfs/entrypoint.sh
  pkg/mounter/ossfs.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#934 chore: add logs for rund expanding
  pkg/disk/utils.go
Labels: kind/cleanup, approved, cncf-cla: yes, size/XS

#936 deploy: remove GA feature gate
  deploy/ecs/csi-provisioner.yaml
Labels: needs-ok-to-test, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#937 feature: support all disk types auto resize
  pkg/disk/controllerserver.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#906 disk: remove the size limit of some categories
  pkg/disk/cloud.go
  pkg/disk/constants.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/M, cncf-cla: yes

#938 chore: bump up vfhp version
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: kind/cleanup, approved, cncf-cla: yes, size/XS
