Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#791 chore: fmt modify
  build/lib/csiplugin-connector.go
  build/oss/csiplugin-connector.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/local/server/commands.go
  pkg/metric/utils.go
  pkg/nas/utils.go
  pkg/oss/utils.go
  pkg/utils/util.go
Labels: lgtm, size/S, kind/cleanup, ok-to-test, cncf-cla: yes

#790 chore: slice replace loop
  pkg/cpfs/controllerserver.go
  pkg/local/capacity.go
  pkg/local/manager/loopdevice.go
  pkg/mem/nodeserver.go
  pkg/nas/controllerserver.go
  pkg/utils/util.go
Labels: lgtm, kind/cleanup, ok-to-test, size/M, cncf-cla: yes

#799 nas: upgrade alinas rpm packages
  build/amd/Dockerfile
  build/lib/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  pkg/nas/nas.go
Labels: size/S, kind/cleanup, ok-to-test, cncf-cla: yes

#800 chore: Add disk controller dockerfile
  build/multi/Dockerfile.controller
Labels: size/S, cncf-cla: yes

#796 bugfix: install different ossfs version for anolis7/8
  build/lib/amd64-entrypoint.sh
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
Labels: kind/bug, lgtm, ok-to-test, size/M, cncf-cla: yes

#802 ossfs update to v1.88.1
  build/amd/Dockerfile
  build/lib/amd64-entrypoint.sh
  build/multi-private/Dockerfile.multi
  build/multi-private/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
Labels: kind/bug, size/S, ok-to-test, cncf-cla: yes

#803 feature: support disk auto detected
  pkg/disk/utils.go
Labels: kind/feature, size/L, cncf-cla: yes

#804 BugFix: fix bdf logics error
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
  pkg/disk/bdf.go
  pkg/disk/nodeserver.go
  pkg/metric/utils.go
Labels: kind/bug, size/M, cncf-cla: yes

#805 Bugfix/fix dfs pov token
  pkg/local/nodeserver.go
  pkg/pov/cloud.go
  pkg/pov/controller.go
Labels: size/M, cncf-cla: yes

#806 fix(nas): skips mounting if target path already mounted
  pkg/nas/nodeserver.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, cncf-cla: yes
