Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#855 rbac: add node patch permission
  deploy/ecs/rbac.yaml
  deploy/nonecs/rbac.yaml
Labels: kind/bug, needs-ok-to-test, lgtm, approved, cncf-cla: yes, size/XS

#857 update external provisioner to v3.5.0
  deploy/ecs/csi-provisioner.yaml
  deploy/ecs/rbac.yaml
  deploy/nonecs/csi-provisioner.yaml
  deploy/nonecs/rbac.yaml
Labels: kind/bug, needs-ok-to-test, kind/documentation, lgtm, size/S, approved, cncf-cla: yes

#856 always force delete disk snapshot
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/M, cncf-cla: yes

#858 adding checks to getInstanceDoc
  pkg/disk/utils.go
Labels: kind/bug, needs-ok-to-test, lgtm, approved, cncf-cla: yes, size/XS

#859 cleanup: delete RemoveAll MkdirAll method
  pkg/metric/fuse_stat_collector.go
  pkg/utils/util.go
Labels: size/S, kind/cleanup, approved, cncf-cla: yes

#860 oss-feat: add ro mount options in ReadOnly mode
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
Labels: lgtm, size/S, approved, cncf-cla: yes

#861 nas: serialize operations on the same volume
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/utils/volume_locks.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#867 Unit test for deleteDisk
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/ecsinterface.go
  pkg/disk/ecsmock.go
Labels: needs-ok-to-test, lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#869 feature: enable bdf check for pov driver
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
  pkg/disk/bdf.go
  pkg/metric/utils.go
Labels: kind/feature, size/S, approved, cncf-cla: yes

#866 disk/ens: optimize AttachMutex
  pkg/disk/cloud.go
  pkg/disk/disk.go
  pkg/ens/ens.go
  pkg/ens/utils.go
Labels: needs-ok-to-test, lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#850 Query API for ECS endpoints in INTERNAL_MODE
  Makefile
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/cloud/utils.go
  pkg/cloud/utils_test.go
  pkg/dbfs/utils.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, lgtm, approved, ok-to-test, size/L, cncf-cla: yes

#872 Bump: bump vfph helper to 0.1.8
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: kind/feature, approved, cncf-cla: yes, size/XS
