Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#939 local: allow volume to be removed from deleted node
  pkg/local/client/grpc.go
  pkg/local/controllerserver.go
  pkg/utils/util.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#886 fix typo reported by misspell
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/utils.go
  pkg/ens/utils.go
  pkg/nas/nodeserver.go
Labels: needs-ok-to-test, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#901 disk: refine attach error codes
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
Labels: needs-ok-to-test, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#941 fix: use "mime" key to compatible with s3fs
  build/fuse-clients/ossfs/install-ossfs.sh
  pkg/mounter/ossfs.go
Labels: lgtm, approved, cncf-cla: yes, size/XS

#943 fix(nas): fix error handling when deleting mounttarget not existing
  pkg/nas/controllerserver.go
  pkg/nas/utils.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#946 [v1.26] disk: fix unmountDuplicateMountPoint to handle no data disk node
  pkg/disk/nodeserver.go
  pkg/utils/mounter.go
Labels: needs-ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#878 store disk type and performance level as slice
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/M, cncf-cla: yes

#949 fix metrics collector panic
  pkg/metric/collector.go
  pkg/metric/kubelet_stats_summary_collector.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#952 Cherry pick #949 fix kubelet stats summary collector panic
  pkg/metric/collector.go
  pkg/metric/kubelet_stats_summary_collector.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#950 skip removal if mountPoint does not exist
  pkg/oss/nodeserver.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#953 disk: fix config file leakage if VolumeDevice is detached from DeleteVolume
  pkg/disk/cloud.go
  pkg/disk/utils.go
Labels: kind/bug, lgtm, approved, ok-to-test, size/M, cncf-cla: yes

#955 support debug level log for ossfs in configmap
  pkg/mounter/ossfs.go
Labels: lgtm, approved, cncf-cla: yes, size/XS

#948 support alibabacloud.com/kms-key-id CreateVolume parameter
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, cncf-cla: yes, size/XS

#957 umount ossfs global mountpoint if corrupted
  pkg/oss/nodeserver.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#920 skip setup for provisioner
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/arm64-entrypoint.sh
Labels: lgtm, size/S, kind/cleanup, approved, ok-to-test, cncf-cla: yes

#961 fix build version injection
  build/multi-private/Dockerfile.multi
  build/multi/Dockerfile.controller
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#960 disk: refined volume count detection
  deploy/ecs/csi-plugin.yaml
  deploy/ecs/csi-provisioner.yaml
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/common/constants.go
  pkg/disk/cloud.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  test/csi-sanity/csi-sanity-disk.yaml
Labels: kind/feature, needs-ok-to-test, size/XL, lgtm, approved, kind/api-change, cncf-cla: yes

#962 enable embed git revision in binary
  .dockerignore
Labels: kind/feature, needs-ok-to-test, lgtm, approved, cncf-cla: yes, size/XS

#905 disk: add tags to ECS snapshot
  pkg/common/constants.go
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
Labels: kind/feature, lgtm, kind/design, approved, ok-to-test, size/L, cncf-cla: yes
