Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#1121 deploy: support customized kubelet root dir
  build/lib/init.sh
  deploy/chart/templates/_utils.tpl
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1126 Add clusterid tag to static provision volume
  pkg/disk/cloud.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1130 disk: skip read xattr for files other than block device
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  pkg/utils/io/device.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1133 build: disable shell in container image
  build/multi/Dockerfile.multi
Labels: cncf-cla: no, kind/cleanup, size/XS

#1129 deploy: refine for disk only deployments
  deploy/chart/templates/plugin.yaml
  deploy/chart/templates/rbac.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1134 disk: fix performance level not effective
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1136 Add new env for private cloud
  deploy/chart/templates/controller.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1137 set x-acsproxy-ascm-context header globally
  pkg/disk/cloud.go
  pkg/disk/utils.go
  pkg/nas/cloud/nas_client_v1.go
  pkg/nas/cloud/nas_client_v2.go
  pkg/nas/filesystem_controller.go
  pkg/utils/http/header.go
  pkg/utils/http/header_test.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1140 deploy: cleanup kubelet root dir and add slash to volumeMounts
  deploy/chart/templates/_utils.tpl
  deploy/chart/templates/plugin.yaml
Labels: lgtm, size/S, approved, cncf-cla: yes

#1138 [1.26] disk: ensure the tags order is consistent
  pkg/disk/cloud.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1118 disk: also cleanup old globalmount at unstage
  pkg/disk/nodeserver.go
Labels: lgtm, approved, cncf-cla: yes, size/XS

#880 disk: remove instant access snapshot params
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/M, cncf-cla: yes

#1116 remove csicommon and bump CSI spec to v1.9
  go.mod
  go.sum
  main.go
  pkg/common/controllerserver.go
  pkg/common/identityserver.go
  pkg/common/nodeserver.go
  pkg/common/start.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/identityserver.go
  pkg/disk/nodeserver.go
  pkg/ens/controllerserver.go
  pkg/ens/ens.go
  pkg/ens/identityserver.go
  pkg/ens/nodeserver.go
  pkg/nas/controllerserver.go
  pkg/nas/controllerserver_test.go
  pkg/nas/filesystem_controller_test.go
  pkg/nas/identity.go
  pkg/nas/identity_test.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
  pkg/pov/controller.go
  pkg/pov/identity.go
  pkg/pov/node.go
  pkg/pov/pov.go
  pkg/testing/proto.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README.md
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go
  vendor/github.com/golang/glog/internal/stackdump/stackdump.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/kubernetes-csi/drivers/LICENSE
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/controllerserver-default.go
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/driver.go
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/identityserver-default.go
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/nodeserver-default.go
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/server.go
  vendor/github.com/kubernetes-csi/drivers/pkg/csi-common/utils.go
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/testing/protocmp/reflect.go
  vendor/google.golang.org/protobuf/testing/protocmp/util.go
  vendor/google.golang.org/protobuf/testing/protocmp/xform.go
  vendor/modules.txt
Labels: lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#1135 disk: support for EED
  pkg/common/constants.go
  pkg/disk/category.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1145 deploy: use new header env
  deploy/chart/templates/controller.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1131 metadata: split ack-cluster-profile to another provider
  pkg/cloud/metadata/ack_cluster_profile.go
  pkg/cloud/metadata/ack_cluster_profile_test.go
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/k8s_test.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1149 chart: add ossfs tag on provisioner
  deploy/chart/templates/controller.yaml
  deploy/chart/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XS

#1128 metadata: ignore empty k8s node label
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/k8s_test.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1147 OSS: set default ossfs default log level to err
  pkg/mounter/fuse_pod_manager.go
  pkg/mounter/fuse_pod_manager_test.go
  pkg/mounter/ossfs.go
  pkg/mounter/ossfs_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#1150 Fix oss mount options parsing
  pkg/oss/nodeserver.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1143 Disable recycle bin check when deleting subpath
  pkg/nas/internal/config.go
  pkg/nas/subpath_controller.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1067 chore: reduce error logs from metrics collector
  pkg/metric/monitor_client.go
Labels: lgtm, size/S, kind/cleanup, approved, lifecycle/stale, cncf-cla: yes

#1146 feat(OSS) rewrite: allow update token by external secret through secretRef
  pkg/mounter/fuse_pod_manager.go
  pkg/mounter/ossfs.go
  pkg/mounter/ossfs_test.go
  pkg/oss/controllerserver.go
  pkg/oss/errors.go
  pkg/oss/nodeserver.go
  pkg/oss/nodeserver_test.go
  pkg/oss/utils.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1123 deploy: only add init container for nas/oss driver
  build/lib/init.sh
  deploy/chart/templates/plugin.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1148 disk: fixes for EED
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  test/e2e-kubernetes/eed-manifest.yaml
  test/e2e-kubernetes/ephemeral-sc.yaml
  test/e2e-kubernetes/run.sh
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1076 disk: also count EED when getAttachedCloudDisks
  pkg/disk/utils.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XS

#1091 init: refine cleaning up old volume staging path
  build/lib/init.sh
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1093 test: update cluster config for 1.30
  test/cluster/cluster-template.json
  test/cluster/cluster-template.jsonnet
  test/cluster/cluster_setup.sh
  test/cluster/gather_logs.sh
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1110 deploy: speed up the rollout
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1120 Support byte-level NAS capacity metrics
  pkg/metric/nfs_stat_collector.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/M, cncf-cla: yes
