Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#1097 Cherry pick #861 nas: serialize operations on the same volume
  pkg/nas/controllerserver.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/utils/volume_locks.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1103 feature: support specific http header
  pkg/disk/cloud.go
  pkg/nas/controllerserver.go
Labels: approved, cncf-cla: yes, size/XS

#1104 oss: support concatenated mountoptions like -ogid=1000,uid=1000
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1105 deploy: optimize controller template
  deploy/chart/templates/controller.yaml
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1028 disk: use xattr to check if the disk is managed by us
  pkg/disk/bdf.go
  pkg/disk/device_manager.go
  pkg/disk/device_manager_test.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  pkg/utils/io/io_darwin.go
  pkg/utils/io/io_linux.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1100 remove dead code
  pkg/disk/constants.go
  pkg/disk/utils.go
  pkg/metric/unix_domain_socket.go
  pkg/pov/cloud.go
  pkg/pov/controller.go
  pkg/utils/auth.go
  pkg/utils/template/template.go
  pkg/utils/util.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1109 feat(OSS): allow customized roleName for STS
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1026 disk: serial detach ad-slot
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
  pkg/disk/cloud.go
  pkg/disk/disk.go
  pkg/features/features.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1112 Nas unit tests
  pkg/nas/accesspoint_controller.go
  pkg/nas/cloud/nas_client_factory.go
  pkg/nas/cloud/nas_client_factory_test.go
  pkg/nas/cloud/nas_client_v1.go
  pkg/nas/cloud/nas_client_v1_test.go
  pkg/nas/cloud/nas_client_v2.go
  pkg/nas/cloud/nas_client_v2_test.go
  pkg/nas/cloud/utils.go
  pkg/nas/cloud/utils_test.go
  pkg/nas/controllerserver_test.go
  pkg/nas/filesystem_controller.go
  pkg/nas/filesystem_controller_test.go
  pkg/nas/identity.go
  pkg/nas/identity_test.go
  pkg/nas/interfaces/nas_client_factory_interface.go
  pkg/nas/interfaces/nas_client_factory_mock.go
  pkg/nas/interfaces/nas_client_v2_interface.go
  pkg/nas/interfaces/nas_client_v2_mock.go
  pkg/nas/interfaces/nas_v1_interface.go
  pkg/nas/interfaces/nas_v1_mock.go
  pkg/nas/interfaces/nas_v2_interface.go
  pkg/nas/interfaces/nas_v2_mock.go
  pkg/nas/internal/config.go
  pkg/nas/internal/config_test.go
  pkg/nas/internal/controller_mock.go
  pkg/nas/internal/controller_mode.go
  pkg/nas/internal/controller_mode_test.go
  pkg/nas/mounter_test.go
  pkg/nas/nas_test.go
  pkg/nas/subpath_controller.go
Labels: lgtm, size/XXL, approved, ok-to-test, cncf-cla: yes

#1090 disk: cleanup old globalmount mounts
  pkg/disk/cleanup.go
  pkg/disk/nodeserver.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1083 disk: refactor create disk
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/disk/category.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#1115 chore: Add new support filesystem type
  pkg/disk/constants.go
  pkg/disk/utils.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XS
