Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#1048 disk: fix sysConfig
  pkg/disk/device_manager.go
  pkg/disk/device_manager_test.go
  pkg/disk/nodeserver.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes, kind/regression

#1051 build: update asi Dockerfile
  build/multi/Dockerfile.multi.asi
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1045 docs,helm: disable controller on non-ECS
  deploy/chart/templates/controller.yaml
  deploy/chart/values-nonecs.yaml
  deploy/chart/values.yaml
  docs/install.md
  docs/nas-dynamic.md
Labels: kind/bug, kind/documentation, lgtm, size/S, approved, cncf-cla: yes

#1053 disk: fix error when mounting parted disks
  pkg/disk/device_manager_test.go
  pkg/disk/utils.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1043 Feature/cherry pick rund csi3.0
  main.go
  pkg/disk/bdf.go
  pkg/disk/device_manager.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/features/features.go
  pkg/nas/internal/config.go
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
  pkg/utils/mounter.go
  pkg/utils/rund/directvolume/direct_volume.go
  pkg/utils/rund/directvolume/utils.go
  pkg/utils/util.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes

#1017 cloud/metadata: retry on http 429
  pkg/cloud/metadata/ecs.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1025 avoid two level of status.Error
  pkg/disk/utils.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1050 helm: remove csinodeinfos from RBAC
  deploy/chart/templates/rbac.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1049 disk/device_manager: replace syscall with unix package
  pkg/disk/device_manager.go
  pkg/disk/device_manager_test.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1055 feautre: add featuregate parameters
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#1058 fix: compatible with the old OSS accelerator endpoint
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: lgtm, size/S, approved, cncf-cla: yes

#1061 fix: rund protocol file path
  pkg/disk/nodeserver.go
  pkg/nas/nodeserver.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1037 helm: add separated local driver
  deploy/chart/Chart.yaml
  deploy/chart/templates/_utils.tpl
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/templates/rbac.yaml
  deploy/chart/values.yaml
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1064 pov driver mount tmpfs when NodePublishVolume
  main.go
  pkg/cloud/metadata/k8s.go
  pkg/pov/node.go
  pkg/pov/pov.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1063 helm: less dependent on /var/lib/kubelet
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
Labels: kind/bug, lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1065 NAS: make rund protocol work without skipmount
  pkg/nas/nodeserver.go
Labels: kind/bug, kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1066 build our own blkid
  build/multi/Dockerfile.multi
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1021 disk: fix false warning about udevadm
  pkg/utils/util.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1042 Kubernetes e2e external storage manifest
  test/e2e-kubernetes/disk-manifest.yaml
Labels: kind/documentation, lgtm, size/S, approved, cncf-cla: yes

#990 don't bring our own nsenter
  .gitignore
  Dockerfile
  build/dbfs/Dockerfile
  build/dbfs/nsenter
  build/lib/amd64-init.sh
  build/lib/amd64-nsenter
  build/lib/arm64-init.sh
  build/lib/arm64-nsenter
  build/multi-private/Dockerfile.multi
  build/multi-private/amd64-entrypoint.sh
  build/multi-private/amd64-nsenter
  build/multi-private/arm64-entrypoint.sh
  build/multi-private/arm64-nsenter
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  docs/migrate/flexvolume-to-csi-disk.md
  docs/migrate/flexvolume-to-csi-empty.md
  pkg/dbfs/utils.go
  pkg/ens/utils.go
  pkg/nas/nodeserver.go
  pkg/utils/util.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/L, cncf-cla: yes

#1032 test: scripts for integration tests and collect coverage
  build/multi/Dockerfile.multi
  main.go
  test/cluster/cluster-template.json
  test/cluster/cluster_setup.sh
  test/cluster/gather_logs.sh
  test/csi-sanity/coverage.yaml
  test/csi-sanity/kustomization.yaml
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1016 disk/ListSnapshots: refactor to comply with CSI
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/L, cncf-cla: yes

#1059 add more reviewers
  OWNERS
Labels: lgtm, approved, cncf-cla: yes, size/XS

#1068 Fix volume setup for rund 2.0
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#902 disk: verify VolumeCapabilities
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/L, kind/api-change, cncf-cla: yes

#1000 disk: support specify disk tags with diskTags/key: value
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/M, cncf-cla: yes
