Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#1201 deploy: remove local
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/csi-driver.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/templates/rbac.yaml
  deploy/chart/templates/storage-class.yaml
  deploy/chart/values-edge.yaml
  deploy/chart/values-external.yaml
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1087 disk: distinguish attach from node/controller
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1202 csi-agent: disable sub-directory check in NodeServerWithValidator
  cmd/csi-agent/main.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1203 Get available disk count from node annotation
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  vendor/k8s.io/mount-utils/mount_unsupported.go
  vendor/k8s.io/mount-utils/resizefs_unsupported.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/L, cncf-cla: yes

#1142 feat: add volume attachment time & csi grpc execution time metrics
  main.go
  pkg/common/interceptors.go
  pkg/common/nodeserver.go
  pkg/common/start.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/ens/ens.go
  pkg/metric/collector.go
  pkg/metric/common.go
  pkg/metric/csi_grpc_exec_time_collector.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/fuse_stat_collector.go
  pkg/metric/metric.go
  pkg/metric/nfs_stat_collector.go
  pkg/metric/volume_stat_collector.go
  pkg/nas/nas.go
  pkg/nas/nodeserver.go
  pkg/oss/nodeserver.go
  pkg/oss/oss.go
  pkg/pov/pov.go
  pkg/utils/util.go
Labels: kind/feature, size/XL, lgtm, approved, ok-to-test, cncf-cla: yes

#1212 deploy/external: fix for OSS driver
  deploy/chart/values-external.yaml
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1204 Fix kubelet restart grpc calling bugs of runD
  pkg/disk/bdf.go
  pkg/disk/nodeserver.go
  pkg/disk/nodeserver_test.go
  pkg/utils/fake_mounter.go
  pkg/utils/rund/directvolume/utils.go
Labels: kind/bug, approved, size/L, cncf-cla: yes

#1219 Revert "deploy: remove local"
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/csi-driver.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/templates/rbac.yaml
  deploy/chart/templates/storage-class.yaml
  deploy/chart/values-edge.yaml
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1205 Private cloud/oss protocol
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1197 bump external-snapshotter to v8.1.0
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1193 cleanup: remove single snapshot request limit logic
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
Labels: lgtm, size/S, approved, cncf-cla: yes

#1195 Cleanups about mount.New()
  pkg/disk/utils.go
  pkg/ens/utils.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/nfs_stat_collector.go
  pkg/utils/util.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1198 deploy: remove snapshot and lease RBAC from node
  deploy/chart/templates/rbac.yaml
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1211 disk: support for Chinese disk name
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1220 disk: disable expand auto snapshot
  pkg/features/features.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS, kind/deprecation

#1191 common: enable contextual logging
  pkg/common/controllerserver.go
  pkg/common/interceptors.go
  pkg/common/nodeserver.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1223 Bump version of golang to 1.22.9
  build/csi-agent/Dockerfile
  build/mount-proxy/Dockerfile
  build/multi-private/Dockerfile.multi
  build/multi/Dockerfile.controller
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  go.mod
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1214 oss: do not modify vpc100 endpoint
  pkg/oss/nodeserver.go
  pkg/oss/nodeserver_test.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1206 docs: enable controller for non-ECS and more
  README-zh_CN.md
  README.md
  deploy/chart/values-nonecs.yaml
  docs/install.md
  docs/oss-upgrade.jpg
  docs/oss-upgrade.md
Labels: kind/documentation, lgtm, approved, size/L, cncf-cla: yes

#1210 disk: create snapshot with client token
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1215 oss: do not modify vpc100 endpoint
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1057 remove mounter.EnsureFolder()
  pkg/disk/nodeserver.go
  pkg/ens/nodeserver.go
  pkg/utils/mounter.go
  pkg/utils/mounter_test.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1194 cleanup: remove snapshot events recorder
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1226 deploy: bump external-provisioner to v5.0.3-aliyun
  deploy/chart/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XS

#1221 Make the OSSFS pod name visible in VolumeAttachment
  pkg/mounter/fuse_pod_manager.go
  pkg/oss/controllerserver.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1207 fix: limit role-session-name for oss rrsa to 64 chars
  pkg/mounter/ossfs.go
  pkg/mounter/ossfs_test.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1216 disk: control the degree of concurrency of attach/detach
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
  pkg/disk/disk.go
  pkg/utils/config.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1208 oss: to keep compatible with cnfs-nas volumeas sharepath
  pkg/oss/utils.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1228 Add dependabot to csi
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, size/XS, kind/regression

#1192 disk: call sfdisk directly to expand partition
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  pkg/disk/nodeserver.go
  pkg/disk/sfdisk/expand.go
  pkg/disk/sfdisk/expand_test.go
  pkg/utils/os/exec.go
  pkg/utils/os/exec_test.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes
