Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#1114 support for regional disk
  pkg/common/constants.go
  pkg/disk/category.go
  pkg/disk/cloud.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  test/e2e-kubernetes/regional-manifest.yaml
  test/e2e-kubernetes/regional-sc.yaml
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1151 deploy: only install fuse namespace if OSS is enabled
  deploy/chart/templates/fuse.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1152 deploy: bump image tags
  deploy/chart/values.yaml
Labels: kind/bug, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1153 test/cluster: use flannel & cleanups
  test/cluster/cluster-template.jsonnet
  test/cluster/cluster_setup.sh
Labels: kind/cleanup, size/M, cncf-cla: yes

#1154 bump csi-provisioner & csi-resizer
  deploy/chart/templates/controller.yaml
  deploy/chart/values.yaml
Labels: kind/feature, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1156 deploy: move DEFAULT_REGISTRY env from local-csi-provisioner to csi-p…
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1158 OSS: bump ossfs version to 1.91.3.ack.3 to fix metrics
  build/mount-proxy/Dockerfile
  deploy/chart/values.yaml
  pkg/mounter/ossfs.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1159 deploy: fix ossfs image name
  deploy/chart/values.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1165 bump golang to 1.19
  build/multi-private/Dockerfile.multi
  build/multi/Dockerfile.controller
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1164 disk: do resizefs regardless of snapshot
  pkg/disk/nodeserver.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1163 disk: use DescribeEndpoints for internal mode
  pkg/cloud/commoninterface.go
  pkg/cloud/ecsinterface.go
  pkg/cloud/ecsmock.go
  pkg/cloud/utils.go
  pkg/cloud/utils_test.go
  pkg/disk/utils.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1171 Fix v1.26 storage-monitor domain name access issue
  deploy/ecs/rbac.yaml
  deploy/nonecs/rbac.yaml
  pkg/metric/http.go
  pkg/metric/monitor_client.go
  pkg/metric/nfs_stat_collector.go
Labels: kind/bug, lgtm, approved, ok-to-test, size/L, cncf-cla: yes

#1175 [v1.26] disk snapshot force delete & instant access backport
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1172 oss: trimspace for ak&sk
  pkg/oss/nodeserver.go
Labels: lgtm, approved, cncf-cla: yes, size/XS

#1169 Don't install iohub-vfhp-helper
  build/lib/init.sh
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1095 doc: update readme
  README-zh_CN.md
  README.md
Labels: kind/documentation, approved, lifecycle/stale, cncf-cla: yes, size/XS
