Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#1178 deploy: fix local external provisioner leader election args
  deploy/chart/templates/controller.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1167 disk: refine error message for rwx filesystem
  pkg/disk/utils.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1157 disk: cleanup formatCSISnapshot
  pkg/disk/controllerserver.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1160 bump csi-attacher to v4.6.1
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1181 Make ack drain skip fuse pods
  pkg/mounter/fuse_pod_manager.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1027 disk: cancel waiting for attach/detach when GRPC cancelled
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1170 disk: avoid concurrent operation on the same disk
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
  pkg/disk/nodeserver.go
  pkg/utils/volume_locks.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1141 Add csi-agent for oss mounting in ACS rund
  build/csi-agent/Dockerfile
  cmd/csi-agent/main.go
  pkg/mounter/proxy/client/client.go
  pkg/oss/csi_agent.go
  pkg/oss/nodeserver.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1174 oss: support get sts endpoint from env for private cloud
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
  pkg/utils/util.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#1180 oss: ossfs bump to 1.91.4 and support OSS signature v4
  build/mount-proxy/Dockerfile
  deploy/chart/values.yaml
  pkg/mounter/ossfs.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: size/XL, lgtm, kind/cleanup, approved, cncf-cla: yes

#1185 oss: cnfs-oss support use subpath
  pkg/common/constants.go
  pkg/nas/filesystem_controller.go
  pkg/nas/sharepath_controller.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
Labels: lgtm, approved, size/M, cncf-cla: yes

#1186 deploy: tune disk sidecar flow control to 2x
  deploy/chart/templates/controller.yaml
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1132 metadata: use ECS security hardening mode
  pkg/cloud/metadata/ecs.go
  pkg/cloud/metadata/ecs_test.go
  pkg/cloud/metadata/metadata_test.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1184 disk: reduce 1 DescribeDisks OpenAPI request on delete
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1182 disk: add a feature gate to disable expand auto snapshot
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/features/features.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes, kind/deprecation

#1187 rename disable-auto-snapshots feature to keep consistent with sidecar
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/features/features.go
Labels: lgtm, size/S, approved, cncf-cla: yes

#1188 disk: rename regional essd to cloud_regional_disk_auto
  pkg/disk/category.go
  test/e2e-kubernetes/regional-sc.yaml
Labels: kind/feature, lgtm, approved, kind/api-change, cncf-cla: yes, size/XS

#1189 deploy: tune oss attacher flow control to 2x
  deploy/chart/templates/controller.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1196 Fix: ossfs mime-support config not work
  build/mount-proxy/Dockerfile
  pkg/mounter/ossfs.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1101 remove special character check
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/ens/controllerserver.go
  pkg/ens/nodeserver.go
  pkg/mounter/fuse_pod_manager_test.go
  pkg/mounter/helper.go
  pkg/nas/controllerserver.go
  pkg/nas/controllerserver_test.go
  pkg/nas/nodeserver.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
  pkg/utils/auth.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1177 Check VBM node type automatically and support csi rund 3.0 protocol
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/metadata.go
  pkg/disk/bdf.go
  pkg/disk/device_manager.go
  pkg/disk/nodeserver.go
Labels: approved, size/L, cncf-cla: yes

#1144 bump CSI spec to v1.10
  go.mod
  go.sum
  pkg/common/controllerserver.go
  pkg/common/identityserver.go
  pkg/common/nodeserver.go
  pkg/pov/controller.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
  vendor/modules.txt
Labels: lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes
