Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-12, with the labels that each got.

#1245 Fix nvme serial id check
  pkg/disk/utils.go
Labels: approved, size/M, cncf-cla: yes

#1246 disk: avoid access metadata server in newEcsClient
  pkg/disk/disk.go
  pkg/disk/utils.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1255 csi-sanity: reduce timeout
  test/csi-sanity/csi-sanity-disk.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1242 test: bump cluster version
  test/cluster/cluster-template.jsonnet
  test/cluster/cluster_setup.sh
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1257 test: fix external ID may has "+"
  test/cluster/cluster_setup.sh
Labels: kind/bug, lgtm, approved, kind/flake, cncf-cla: yes, size/XS

#1249 feature/switch_to_new_token
  deploy/chart/templates/controller.yaml
  deploy/chart/values-external.yaml
  deploy/chart/values.yaml
Labels: kind/cleanup, approved, cncf-cla: yes, size/XS

#1155 test/cluster: add node for EED
  test/cluster/cluster-template.jsonnet
  test/cluster/cluster_setup.sh
Labels: lgtm, size/S, approved, cncf-cla: yes

#1256 deploy: bump image version to release v1.6.1
  deploy/chart/values.yaml
  test/csi-sanity/csi-sanity-disk.yaml
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1264 metric/disk: fix disk size reporting
  pkg/metric/utils.go
  pkg/metric/utils_test.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes, kind/regression

#1265 deploy: enable oss controller for edge
  deploy/chart/values-edge.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XS

#1258 test: avoid warning
  test/cluster/cluster_setup.sh
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1261 disk: remove support for multi-tenancy
  pkg/disk/bdf.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/utils/auth.go
Labels: lgtm, kind/cleanup, approved, size/L, kind/api-change, cncf-cla: yes

#1244 disk: fix unit test
  pkg/disk/nodeserver_test.go
Labels: kind/failing-test, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1247 disk: remove createDest
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1250 disk: also check for VolumeCapability when expand
  pkg/disk/nodeserver.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1243 disk: allow skip updating diskType label for existing node
  pkg/disk/constants.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1239 disk remove MaxVolumesPerNodeLimit
  pkg/disk/nodeserver.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1240 remove dep on old github.com/golang/protobuf
  go.mod
  pkg/disk/controllerserver.go
  pkg/disk/group_volume_snapshot_utils.go
  pkg/disk/group_volume_snapshot_utils_test.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1098 build: rewrite dockerfile to distroless
  build/build-all-multi.sh
  build/gather-node-deps.sh
  build/lib/init.sh
  build/multi/Dockerfile.multi
  hack/base-image-deps.txt
  hack/update-base-image-deps.sh
  hack/update-dockerfile.sh
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1213 disk: remove expand auto snapshot
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/features/features.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes, kind/deprecation

#1276 add a check-helm-kind makefile target
  .gitignore
  Makefile
  hack/check-vendor.sh
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1277 fix helm install
  Makefile
Labels: kind/bug, kind/failing-test, lgtm, approved, cncf-cla: yes, size/XS

#964 Improve build reproducibility
  build/csi-agent/Dockerfile
  build/multi/Dockerfile.controller
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  cmd/csi-agent/main.go
  main.go
  pkg/version/version.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/M, cncf-cla: yes

#1009 disk: DescribeDisks auto batching
  pkg/cloud/throttle/throttle.go
  pkg/cloud/throttle/throttle_test.go
  pkg/disk/batcher/interface.go
  pkg/disk/batcher/low_latency.go
  pkg/disk/batcher/low_latency_test.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/desc/describe.go
  pkg/disk/desc/testing/fake.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/waitstatus/batched.go
  pkg/disk/waitstatus/batched_test.go
  pkg/disk/waitstatus/interface.go
  pkg/disk/waitstatus/interface_test.go
  pkg/disk/waitstatus/simple.go
Labels: kind/feature, lgtm, kind/cleanup, size/XXL, approved, ok-to-test, cncf-cla: yes

#1273 deploy: bump snapshot controller to v8.1.1
  deploy/chart/values.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1284 Change plugin token name
  deploy/chart/templates/plugin.yaml
Labels: approved, cncf-cla: yes, size/XS

#1281 Ossfs/1.91.5 release
  build/csi-agent/Dockerfile
  build/fuse-clients/ossfs/Dockerfile
  build/fuse-clients/ossfs/entrypoint.sh
  build/fuse-clients/ossfs/install-ossfs.sh
  build/mount-proxy/Dockerfile
  deploy/chart/values.yaml
  pkg/mounter/ossfs.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1286 Add values
  deploy/chart/values.yaml
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#1287 Modified use newToken configuration name
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values-external.yaml
  deploy/chart/values.yaml
Labels: size/S, kind/cleanup, approved, cncf-cla: yes
