Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#965 update issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: needs-ok-to-test, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#963 fix: configure mlocate cron.daily
  build/lib/amd64-entrypoint.sh
  build/lib/arm64-entrypoint.sh
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#967 disk: set IO limit before mount
  pkg/disk/nodeserver.go
  pkg/ens/nodeserver.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, approved, cncf-cla: yes

#930 disk: wait to serialize attach & detach
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
Labels: kind/feature, needs-ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#971 cleanup: Remove useless code module
  build/lvm/Dockerfile
  build/lvm/entrypoint.sh
  build/lvm/nsenter
  build/mem/Dockerfile
  examples/lvm/deploy.yaml
  examples/lvm/hapv/storageclass.yaml
  examples/lvm/pvc.yaml
  examples/lvm/resizer/storageclass.yaml
  examples/lvm/storageclass.yaml
  examples/lvm/striping/pvc.yaml
  examples/lvm/striping/storageclass.yaml
  examples/lvm/topology/storageclass.yaml
  examples/mem/deploy.yaml
  examples/mem/pv.yaml
  examples/mem/pvc.yaml
  examples/mem/storageclass.yaml
  main.go
  pkg/lvm/controllerserver.go
  pkg/lvm/identityserver.go
  pkg/lvm/lvm.go
  pkg/lvm/nodeserver.go
  pkg/lvm/utils.go
  pkg/lvm/utils_test.go
  pkg/lvm/vgcreate.sh
  pkg/mem/controllerserver.go
  pkg/mem/identityserver.go
  pkg/mem/mem.go
  pkg/mem/nodeserver.go
  pkg/mem/types.go
  pkg/mem/utils.go
  pkg/mem/utils_test.go
  tools/disk-auto-init/main.go
Labels: kind/cleanup, size/XXL, approved, cncf-cla: yes

#854 batch dead code removal
  build/lib/csiplugin-connector.go
  build/multi-private/csiplugin-connector.go
  main.go
  pkg/cpfs/cpfs.go
  pkg/dbfs/controllerserver.go
  pkg/dbfs/dbfs.go
  pkg/dbfs/nodeserver.go
  pkg/dbfs/utils.go
  pkg/disk/bdf.go
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/disk.go
  pkg/ens/ens.go
  pkg/ens/nodeserver.go
  pkg/local/local.go
  pkg/local/utils.go
  pkg/nas/utils.go
  pkg/om/blockvolume.go
  pkg/oss/controllerserver.go
  pkg/oss/utils.go
  pkg/utils/mounter.go
  pkg/utils/util.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/L, cncf-cla: yes

#974 remove pkg/log
  go.mod
  go.sum
  main.go
  pkg/dbfs/controllerserver.go
  pkg/dbfs/dbfs.go
  pkg/dbfs/nodeserver.go
  pkg/dbfs/utils.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/local/capacity.go
  pkg/log/formatter.go
  pkg/log/log.go
  pkg/pov/cloud.go
  pkg/pov/controller.go
  vendor/github.com/lestrrat-go/file-rotatelogs/.gitignore
  vendor/github.com/lestrrat-go/file-rotatelogs/.travis.yml
  vendor/github.com/lestrrat-go/file-rotatelogs/Changes
  vendor/github.com/lestrrat-go/file-rotatelogs/LICENSE
  vendor/github.com/lestrrat-go/file-rotatelogs/README.md
  vendor/github.com/lestrrat-go/file-rotatelogs/event.go
  vendor/github.com/lestrrat-go/file-rotatelogs/interface.go
  vendor/github.com/lestrrat-go/file-rotatelogs/internal/option/option.go
  vendor/github.com/lestrrat-go/file-rotatelogs/options.go
  vendor/github.com/lestrrat-go/file-rotatelogs/rotatelogs.go
  vendor/github.com/lestrrat-go/strftime/.gitignore
  vendor/github.com/lestrrat-go/strftime/.golangci.yml
  vendor/github.com/lestrrat-go/strftime/Changes
  vendor/github.com/lestrrat-go/strftime/LICENSE
  vendor/github.com/lestrrat-go/strftime/Makefile
  vendor/github.com/lestrrat-go/strftime/README.md
  vendor/github.com/lestrrat-go/strftime/appenders.go
  vendor/github.com/lestrrat-go/strftime/extension.go
  vendor/github.com/lestrrat-go/strftime/internal/errors/errors_fmt.go
  vendor/github.com/lestrrat-go/strftime/internal/errors/errors_pkg.go
  vendor/github.com/lestrrat-go/strftime/options.go
  vendor/github.com/lestrrat-go/strftime/specifications.go
  vendor/github.com/lestrrat-go/strftime/strftime.go
  vendor/github.com/rifflock/lfshook/LICENSE
  vendor/github.com/rifflock/lfshook/README.md
  vendor/github.com/rifflock/lfshook/lfshook.go
  vendor/modules.txt
Labels: needs-ok-to-test, lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#973 disk: support running provisioner without ECS metadata
  pkg/cloud/metadata/ecs.go
  pkg/cloud/metadata/metadata.go
  pkg/disk/disk.go
Labels: kind/bug, needs-ok-to-test, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes, kind/regression

#976 Revert "Unified loopdevice name"
  pkg/local/capacity.go
Labels: approved, cncf-cla: yes, size/XS

#977 fix panic when using parallel attach detach
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
Labels: kind/bug, lgtm, approved, ok-to-test, size/M, cncf-cla: yes

#978 feature: support specific http header
  pkg/disk/cloud.go
  pkg/nas/controllerserver.go
Labels: kind/feature, approved, cncf-cla: yes, size/XS

#980 bug: fix string float conversion
  pkg/local/capacity.go
Labels: kind/bug, approved, cncf-cla: yes, size/XS

#983 chore: refact token decrypt
  pkg/utils/auth.go
  pkg/utils/crypto/aes.go
  pkg/utils/crypto/ramtoken.go
Labels: kind/cleanup, approved, size/L, cncf-cla: yes

#984 disk: fallback on unsupported PL
  pkg/disk/cloud.go
  pkg/disk/constants.go
Labels: kind/bug, needs-ok-to-test, lgtm, approved, cncf-cla: yes, size/XS
