Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1073 disk: ensure the tags order is consistent
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, do-not-merge/hold, lgtm, approved, size/L, cncf-cla: yes

#1070 test: dereference while gather logs
  test/cluster/gather_logs.sh
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1077 local: bump to v0.1.0
  deploy/chart/values.yaml
Labels: kind/bug, kind/feature, lgtm, approved, cncf-cla: yes, size/XS

#1072 combine the init script of different arch into one
  build/lib/arm64-init.sh
  build/lib/init.sh
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1047 helm: nas driver no longer needs /mnt
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1078 Add support for ACK-one register clusters
  deploy/chart/templates/_utils.tpl
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values-external.yaml
  deploy/chart/values.yaml
  pkg/nas/subpath_controller.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1082 ossfs: bump to 1.91.3
  pkg/mounter/ossfs.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XS

#1075 bump golang to 1.22.3
  build/multi-private/Dockerfile.multi
  build/multi/Dockerfile.controller
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  go.mod
  go.sum
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1079 build: install alinas-utils on Ubuntu
  build/lib/init.sh
  build/multi/Dockerfile.multi
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1084 Remove SPM and non-ascii chars in log
  docs/migrate/flexvolume-to-csi-disk.md
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/metric/disk_stat_collector.go
  pkg/utils/error_types.go
  pkg/utils/error_types_test.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/M, cncf-cla: yes

#1080 doc: add ram policy example for nas driver
  docs/ram-policies/nas.json
Labels: kind/documentation, lgtm, approved, size/M, cncf-cla: yes

#1085 update alinas-utils rpm package to support tls mount on alinux3
  build/lib/init.sh
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
Labels: kind/feature, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1081 CGroup V2 support
  deploy/chart/templates/plugin.yaml
  pkg/disk/bdf.go
  pkg/disk/device_manager.go
  pkg/disk/device_manager_test.go
  pkg/disk/nodeserver.go
  pkg/ens/nodeserver.go
  pkg/utils/cgroup/io.go
  pkg/utils/cgroup/io_test.go
  pkg/utils/cgroup/pod.go
  pkg/utils/cgroup/pod_test.go
  pkg/utils/io.go
  pkg/utils/io/device.go
  pkg/utils/io/file.go
  pkg/utils/io/file_test.go
  pkg/utils/io/io_darwin.go
  pkg/utils/io/io_linux.go
  pkg/utils/io_darwin.go
  pkg/utils/io_test.go
  pkg/utils/util.go
Labels: kind/feature, size/XL, lgtm, approved, cncf-cla: yes

#1086 bugfix: Fix IsVFNode check error in provisioner
  pkg/disk/cloud.go
  pkg/disk/disk.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1088 Fix helm upgrade
  deploy/chart/templates/plugin.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1089 deploy: ensure daemonset can upgrade
  deploy/chart/templates/plugin.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1092 init: fix restart and downgrade for yum
  build/lib/init.sh
Labels: kind/bug, lgtm, approved, size/M, cncf-cla: yes

#1094 no longer use /mnt as tmp mount path
  pkg/nas/nodeserver.go
  pkg/nas/utils.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS
