Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#1358 Fix tags logics
  pkg/disk/utils.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1355 [bug]Forbid empty zoneId request for disk
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, approved, size/M, cncf-cla: yes

#1360 re-enable metric for controller
  main.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1357 Add cnfs-nas-daemon support in mount-proxy
  build/mount-proxy/Dockerfile
  deploy/chart/templates/plugin.yaml
  pkg/mounter/proxy/server/alinas/driver.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1217 common: make instrumentGRPC return interceptor
  pkg/common/interceptors.go
  pkg/common/start.go
Labels: lifecycle/rotten, lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1347 utils: fix serviceType log
  pkg/utils/util.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1179 Access ECS OpenAPI using the VPC endpoint on ECS
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  pkg/disk/utils.go
Labels: lifecycle/rotten, lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1362 oss: support passing mount options through environment variables
  pkg/mounter/ossfs.go
Labels: kind/feature, lgtm, size/S, approved, ok-to-test, cncf-cla: yes

#1364 oss: adjust controller api qps& burst
  deploy/chart/templates/controller.yaml
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1365 deploy: add quote to deal with strange path
  deploy/chart/templates/_utils.tpl
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1366 bump base image
  build/multi/Dockerfile.multi
  hack/base-image-deps.txt
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1380 backport(oss): support ossfs1.91.5 by ENV
  build/amd/Dockerfile
  build/lib/amd64-entrypoint.sh
  build/multi-private/Dockerfile.multi
  build/multi-private/amd64-entrypoint.sh
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1381 bump local to v0.2.0
  deploy/chart/values.yaml
Labels: kind/bug, lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1382 backport: allow get regionID from ENV
  pkg/disk/disk.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1383 deploy: add value deploy.network
  deploy/chart/templates/_utils.tpl
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes
