Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-08, with the labels that each got.

#1483 Fix oss rrsa mount issue
  pkg/oss/nodeserver.go
Labels: kind/bug, lgtm, approved, ok-to-test, cncf-cla: yes, size/XS

#996 Refactor credential acquisition (part 1)
  pkg/credentials/credential.go
  pkg/credentials/credential_test.go
  pkg/credentials/managed_token.go
  pkg/credentials/managed_token_test.go
  pkg/utils/auth.go
  pkg/utils/crypto/ramtoken.go
  pkg/utils/crypto/ramtoken_test.go
  pkg/utils/crypto/testing/test_ramtoken.go
Labels: lgtm, kind/cleanup, approved, ok-to-test, size/L, cncf-cla: yes

#1494 oss: tolerate no regionID
  pkg/oss/utils.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS, kind/regression
