Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#1410 oss: use internal endpoint only for VPC network
  pkg/disk/utils.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
  pkg/utils/global.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1409 write csi-sanity junit report to hostPath
  test/csi-sanity/csi-sanity-disk.yaml
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1402 docs: non-ECS cluster needs regionID to be specified
  docs/install.md
Labels: kind/documentation, lgtm, approved, cncf-cla: yes, size/XS

#1373 fix typo
  main.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1418 remove unused getInstanceDoc
  go.mod
  go.sum
  pkg/disk/constants.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  vendor/github.com/h2non/parth/LICENSE
  vendor/github.com/h2non/parth/README.md
  vendor/github.com/h2non/parth/parth.go
  vendor/github.com/h2non/parth/segindex.go
  vendor/github.com/h2non/parth/segtostr.go
  vendor/gopkg.in/h2non/gock.v1/.editorconfig
  vendor/gopkg.in/h2non/gock.v1/.gitignore
  vendor/gopkg.in/h2non/gock.v1/.travis.yml
  vendor/gopkg.in/h2non/gock.v1/History.md
  vendor/gopkg.in/h2non/gock.v1/LICENSE
  vendor/gopkg.in/h2non/gock.v1/README.md
  vendor/gopkg.in/h2non/gock.v1/gock.go
  vendor/gopkg.in/h2non/gock.v1/matcher.go
  vendor/gopkg.in/h2non/gock.v1/matchers.go
  vendor/gopkg.in/h2non/gock.v1/mock.go
  vendor/gopkg.in/h2non/gock.v1/options.go
  vendor/gopkg.in/h2non/gock.v1/request.go
  vendor/gopkg.in/h2non/gock.v1/responder.go
  vendor/gopkg.in/h2non/gock.v1/response.go
  vendor/gopkg.in/h2non/gock.v1/store.go
  vendor/gopkg.in/h2non/gock.v1/transport.go
  vendor/gopkg.in/h2non/gock.v1/version.go
  vendor/modules.txt
Labels: lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#1405 disk: refactor determine ZoneID
  build/csi-agent/Dockerfile
  build/mount-proxy/Dockerfile
  build/multi/Dockerfile.multi
  build/multi/Dockerfile.multi.asi
  go.mod
  pkg/cloud/metadata/ack_cluster_profile.go
  pkg/cloud/metadata/ack_cluster_profile_test.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/disk/controllerserver.go
  pkg/disk/disk.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
Labels: kind/bug, lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1421 adapt to error message change
  pkg/utils/auth.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1419 nas: use cloud/metadata
  pkg/nas/accesspoint_controller.go
  pkg/nas/filesystem_controller.go
  pkg/nas/filesystem_controller_test.go
  pkg/nas/internal/config.go
  pkg/nas/subpath_controller.go
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1384 batch fix vet and go-staticcheck warnings
  pkg/disk/bdf.go
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/group_volume_snapshot_utils.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/metric/common.go
  pkg/metric/nfs_stat_collector.go
  pkg/metric/utils.go
  pkg/nas/filesystem_controller.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1427 disk: fix expand parted
  pkg/disk/nodeserver.go
  pkg/disk/sfdisk/expand.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes

#1394 ossfs2: set default logdir to /dev/stdout
  pkg/mounter/oss/ossfs.go
  pkg/mounter/oss/ossfs2.go
  pkg/mounter/oss/ossfs2_test.go
  pkg/mounter/oss/ossfs_test.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1406 nas: make 'standard' the default NAS file system type
  pkg/nas/cloud/utils.go
  pkg/nas/cloud/utils_test.go
Labels: kind/bug, lgtm, size/S, approved, ok-to-test, cncf-cla: yes

#1368 bump registrar to v2.14.0
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1371 bump external-provisioner to v5.3.0
  deploy/chart/templates/controller.yaml
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1428 Update dockerfile
  .github/workflows/update-dockerfile.yaml
  Makefile
  build/multi/Dockerfile.multi
  hack/base-image-deps.txt
  hack/update-dockerfile.sh
Labels: lgtm, kind/cleanup, approved, size/M, cncf-cla: yes

#1426 feat:support cloud essd with new disk type as xc0 and xc1
  pkg/disk/category.go
  pkg/disk/cloud_test.go
Labels: kind/feature, lgtm, size/S, approved, ok-to-test, cncf-cla: yes

#1434 docs(OSS): add client selection reference in doc/oss.md
  docs/oss.md
Labels: kind/documentation, lgtm, size/S, approved, cncf-cla: yes
