Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#1313 Remove get metadata server from ECS client initialization
  pkg/disk/disk.go
  pkg/disk/utils.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1314 Add typo check
  .github/workflows/typos.yaml
  _typos.toml
  cmd/csi-agent/main.go
  docs/nas-dynamic.md
  pkg/agent/queryserver.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/utils_test.go
  pkg/disk/attachdetach_slot.go
  pkg/disk/attachdetach_slot_test.go
  pkg/disk/batcher/low_latency.go
  pkg/disk/bdf.go
  pkg/disk/bdfcheck.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/device_manager.go
  pkg/disk/group_volume_snapshot_utils.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/disk/utils_test.go
  pkg/ens/ens.go
  pkg/ens/nodeserver.go
  pkg/ens/utils.go
  pkg/metric/utils.go
  pkg/mounter/fuse_pod_manager.go
  pkg/mounter/helper.go
  pkg/mounter/ossfs.go
  pkg/nas/cloud/nas_client_v2_test.go
  pkg/nas/nodeserver.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
  pkg/oss/utils_test.go
  pkg/pov/cloud.go
  pkg/pov/controller.go
  pkg/pov/internal/inflight.go
  pkg/utils/error_types.go
  pkg/utils/error_types_test.go
  pkg/utils/http/header.go
  pkg/utils/util.go
Labels: kind/cleanup, approved, size/L, cncf-cla: yes

#1307 disk: wait for device to appear on attach
  pkg/disk/cloud.go
  pkg/disk/device_manager.go
  pkg/disk/device_manager_test.go
  pkg/disk/nodeserver.go
Labels: lgtm, kind/cleanup, approved, kind/flake, size/L, cncf-cla: yes

#1318 chart: add nasEndpoint setting in values
  deploy/chart/templates/controller.yaml
  deploy/chart/templates/plugin.yaml
  deploy/chart/values.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1320 build: omit debug info by default
  build/multi/Dockerfile.multi
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1279 Cleanup all non-constant printf format string
  pkg/disk/bdfcheck.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/nodeserver.go
  pkg/disk/utils.go
  pkg/ens/nodeserver.go
  pkg/ens/utils.go
  pkg/nas/nodeserver.go
  pkg/nas/subpath_controller.go
  pkg/oss/controllerserver.go
  pkg/oss/nodeserver.go
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1280 test: fix external ID started with "-"
  test/cluster/cluster_setup.sh
Labels: kind/bug, lgtm, approved, kind/flake, cncf-cla: yes, size/XS

#1323 disk: refuse to delete disk on ECI
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1278 csi-agent: add support for nas driver
  build/csi-agent/Dockerfile
  cmd/csi-agent/main.go
  cmd/mount-proxy-server/main.go
  pkg/mounter/proxy/server/alinas/mount_handler.go
  pkg/mounter/proxy/server/handler.go
  pkg/mounter/proxy/server/mount.go
  pkg/mounter/proxy/server/ossfs/mount_handler.go
  pkg/nas/csi_agent.go
  pkg/nas/internal/config.go
  pkg/nas/mounter.go
  pkg/nas/mounter_test.go
  pkg/nas/nodeserver.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1324 disk: refuse to delete disk on ACS
  pkg/disk/controllerserver.go
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS

#1316 support -kube-api-qps and -kube-api-burst flags, unify all client config
  cmd/csi-agent/main.go
  cmd/mount-proxy-client/main.go
  cmd/mount-proxy-server/main.go
  deploy/chart/templates/controller.yaml
  go.mod
  main.go
  pkg/agent/queryserver.go
  pkg/disk/disk.go
  pkg/ens/ens.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/nfs_stat_collector.go
  pkg/options/genericoptions.go
  pkg/pov/pov.go
  pkg/utils/global.go
  pkg/utils/util.go
Labels: kind/feature, lgtm, approved, size/L, cncf-cla: yes

#1168 Tune sidecar client-side flow control
  deploy/chart/templates/controller.yaml
Labels: lifecycle/rotten, lgtm, size/S, approved, cncf-cla: yes

#1319 Fix golangci lint error
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  main.go
  pkg/agent/queryserver.go
  pkg/cloud/metadata/ecs.go
  pkg/common/interceptors.go
  pkg/common/start.go
  pkg/dadi/dadi.go
  pkg/disk/attach_helper.go
  pkg/disk/bdf.go
  pkg/disk/bdfcheck.go
  pkg/disk/cloud.go
  pkg/disk/group_volume_snapshot_utils_test.go
  pkg/disk/nodeserver.go
  pkg/disk/nodeserver_test.go
  pkg/disk/utils.go
  pkg/ens/nodeserver.go
  pkg/ens/openapi.go
  pkg/ens/utils.go
  pkg/metric/nfs_stat_collector.go
  pkg/metric/utils.go
  pkg/mounter/fuse_pod_manager.go
  pkg/mounter/proxy/server/ossfs/mount_handler.go
  pkg/om/om.go
  pkg/oss/coco.go
  pkg/oss/controllerserver.go
  pkg/pov/cloud.go
  pkg/utils/util.go
Labels: kind/cleanup, approved, size/L, cncf-cla: yes

#1331 oss: use stat to detect mountpoint
  pkg/mounter/proxy_mounter.go
  pkg/oss/nodeserver.go
  pkg/oss/utils.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1334 V1.26 disk perf
  build/multi/Dockerfile.multi
  go.mod
  go.sum
  pkg/disk/batcher/interface.go
  pkg/disk/batcher/low_latency.go
  pkg/disk/batcher/low_latency_test.go
  pkg/disk/cloud.go
  pkg/disk/controllerserver.go
  pkg/disk/desc/describe.go
  pkg/disk/desc/testing/fake.go
  pkg/disk/disk.go
  pkg/disk/nodeserver.go
  pkg/disk/waitstatus/batched.go
  pkg/disk/waitstatus/batched_test.go
  pkg/disk/waitstatus/interface.go
  pkg/disk/waitstatus/interface_test.go
  pkg/disk/waitstatus/simple.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: kind/feature, lgtm, size/XXL, approved, cncf-cla: yes

#1325 [v1.26] disk: avoid concurrent operation on the same disk
  pkg/disk/nodeserver.go
Labels: kind/bug, lgtm, size/S, approved, cncf-cla: yes
