Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#1225 disk/snapshot: wait for cut
  pkg/disk/cloud.go
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1293 feat(disk): add region and zone labels to disk PV
  pkg/disk/disk.go
  pkg/disk/utils.go
Labels: lgtm, approved, ok-to-test, cncf-cla: yes, size/XS

#1333 Bump deps
  build/multi/Dockerfile.multi
  hack/base-image-deps.tpl
  hack/base-image-deps.txt
  hack/update-base-image-deps.sh
  hack/update-test-cluster.sh
  test/cluster/cluster-template.jsonnet
  test/cluster/cluster_setup.sh
Labels: lgtm, kind/cleanup, approved, size/L, cncf-cla: yes

#1292 bump local to v0.1.3
  deploy/chart/values.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1335 metadata: if value in cluster profile is empty, return error
  pkg/cloud/metadata/ack_cluster_profile.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1336 fix: use long form for flags when create ossfs pod to keep conpatible with pflag
  pkg/mounter/ossfs.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1317 remove node check (for vk) and serviceaccount check
  deploy/chart/templates/fuse.yaml
  pkg/mounter/fuse_pod_manager.go
  pkg/oss/controllerserver.go
Labels: lgtm, size/S, kind/cleanup, approved, cncf-cla: yes

#1289 disk: fix sfdisk for in-use disk
  build/gather-node-deps.sh
  build/multi/Dockerfile.multi
  pkg/disk/sfdisk/expand.go
  pkg/disk/sfdisk/expand_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: kind/bug, lgtm, size/XXL, approved, cncf-cla: yes

#1343 feat(nas): support mounting through cnfs-alinas-daemon
  pkg/features/features.go
  pkg/nas/internal/config.go
Labels: kind/feature, lgtm, size/S, approved, cncf-cla: yes

#1046 metric: disk hang alert and some cleanup
  pkg/metric/common.go
  pkg/metric/disk_stat_collector.go
  pkg/metric/nfs_stat_collector.go
  pkg/metric/proc_diskstats.go
  pkg/metric/proc_diskstats_test.go
  pkg/metric/utils.go
  vendor/github.com/prometheus/procfs/blockdevice/stats.go
  vendor/modules.txt
Labels: kind/feature, lgtm, kind/cleanup, size/XXL, approved, cncf-cla: yes

#1342 feat(disk): support creating EED for VK
  pkg/common/constants.go
  pkg/disk/cloud.go
  pkg/disk/cloud_test.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: kind/feature, lgtm, approved, ok-to-test, size/M, cncf-cla: yes

#1346 disk: skip most parameter verification for static volume
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes
