Repository kubernetes-sigs/alibaba-cloud-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#1294 fix(build): mount.nfs failed
  build/gather-node-deps.sh
  hack/base-image-deps.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XS

#1282 hack: support update base image deps with docker
  Makefile
  hack/update-base-image-deps.sh
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1290 [v1.26] disk: remove expand auto snapshot
  Makefile
  hack/check-vendor.sh
  pkg/disk/constants.go
  pkg/disk/controllerserver.go
  pkg/disk/utils.go
Labels: kind/bug, lgtm, approved, size/L, cncf-cla: yes

#1301 Fix idempotent issue of runD mounted
  pkg/disk/nodeserver.go
  pkg/disk/nodeserver_test.go
Labels: kind/bug, approved, size/L, cncf-cla: yes

#1306 support enable delete auto snapshots by featuregate for managedprovis…
  pkg/disk/disk.go
  pkg/features/features.go
Labels: kind/feature, lgtm, approved, size/M, cncf-cla: yes

#1296 deploy: increase the limit of init container
  deploy/chart/templates/plugin.yaml
Labels: lgtm, kind/cleanup, approved, cncf-cla: yes, size/XS
